// Code generated by encx-gen. DO NOT EDIT.
// Source: case.go
// Generated: 2025-12-26T19:03:06+01:00

package caseDomain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// CaseEncx represents the encrypted version of Case
type CaseEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	ClientID uuid.UUID `db:"clientid" json:"clientid"`
	
	AssignedContactID *uuid.UUID `db:"assignedcontactid" json:"assignedcontactid"`
	
	CaseType string `db:"casetype" json:"casetype"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	TitleEncrypted []byte `db:"title_encrypted" json:"title_encrypted"`
	
	DescriptionEncrypted []byte `db:"description_encrypted" json:"description_encrypted"`
	
	ExternalReferenceEncrypted []byte `db:"externalreference_encrypted" json:"externalreference_encrypted"`
	
	StatusEncrypted []byte `db:"status_encrypted" json:"status_encrypted"`
	
	UpdatedAtEncrypted []byte `db:"updatedat_encrypted" json:"updatedat_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessCaseEncx encrypts and hashes fields based on encx tags
func ProcessCaseEncx(ctx context.Context, crypto encx.CryptoService, source *Case) (*CaseEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &CaseEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ClientID = source.ClientID
	
	result.AssignedContactID = source.AssignedContactID
	
	result.CaseType = source.CaseType
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Title (encrypt)
	TitleBytes, err := encx.SerializeValue(source.Title)
	if err != nil {
		errs.Set("Title serialization", err)
	} else {
		result.TitleEncrypted, err = crypto.EncryptData(ctx, TitleBytes, dek)
		if err != nil {
			errs.Set("Title encryption", err)
		}
	}
	
	
	
	// Process Description (encrypt)
	DescriptionBytes, err := encx.SerializeValue(source.Description)
	if err != nil {
		errs.Set("Description serialization", err)
	} else {
		result.DescriptionEncrypted, err = crypto.EncryptData(ctx, DescriptionBytes, dek)
		if err != nil {
			errs.Set("Description encryption", err)
		}
	}
	
	
	
	// Process ExternalReference (encrypt)
	if source.ExternalReference != nil {
	ExternalReferenceBytes, err := encx.SerializeValue(source.ExternalReference)
	if err != nil {
		errs.Set("ExternalReference serialization", err)
	} else {
		result.ExternalReferenceEncrypted, err = crypto.EncryptData(ctx, ExternalReferenceBytes, dek)
		if err != nil {
			errs.Set("ExternalReference encryption", err)
		}
	}
	}
	
	
	
	// Process Status (encrypt)
	StatusBytes, err := encx.SerializeValue(source.Status)
	if err != nil {
		errs.Set("Status serialization", err)
	} else {
		result.StatusEncrypted, err = crypto.EncryptData(ctx, StatusBytes, dek)
		if err != nil {
			errs.Set("Status encryption", err)
		}
	}
	
	
	
	// Process UpdatedAt (encrypt)
	if !source.UpdatedAt.IsZero() {
	UpdatedAtBytes, err := encx.SerializeValue(source.UpdatedAt)
	if err != nil {
		errs.Set("UpdatedAt serialization", err)
	} else {
		result.UpdatedAtEncrypted, err = crypto.EncryptData(ctx, UpdatedAtBytes, dek)
		if err != nil {
			errs.Set("UpdatedAt encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptCaseEncx decrypts the encrypted struct back to original
func DecryptCaseEncx(ctx context.Context, crypto encx.CryptoService, source *CaseEncx) (*Case, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Case{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ClientID = source.ClientID
	
	result.AssignedContactID = source.AssignedContactID
	
	result.CaseType = source.CaseType
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Title
	if len(source.TitleEncrypted) > 0 {
		TitleBytes, err := crypto.DecryptData(ctx, source.TitleEncrypted, dek)
		if err != nil {
			errs.Set("Title decryption", err)
		} else {
			err = encx.DeserializeValue(TitleBytes, &result.Title)
			if err != nil {
				errs.Set("Title deserialization", err)
			}
		}
	}
	
	
	// Decrypt Description
	if len(source.DescriptionEncrypted) > 0 {
		DescriptionBytes, err := crypto.DecryptData(ctx, source.DescriptionEncrypted, dek)
		if err != nil {
			errs.Set("Description decryption", err)
		} else {
			err = encx.DeserializeValue(DescriptionBytes, &result.Description)
			if err != nil {
				errs.Set("Description deserialization", err)
			}
		}
	}
	
	
	// Decrypt ExternalReference
	if len(source.ExternalReferenceEncrypted) > 0 {
		ExternalReferenceBytes, err := crypto.DecryptData(ctx, source.ExternalReferenceEncrypted, dek)
		if err != nil {
			errs.Set("ExternalReference decryption", err)
		} else {
			err = encx.DeserializeValue(ExternalReferenceBytes, &result.ExternalReference)
			if err != nil {
				errs.Set("ExternalReference deserialization", err)
			}
		}
	}
	
	
	// Decrypt Status
	if len(source.StatusEncrypted) > 0 {
		StatusBytes, err := crypto.DecryptData(ctx, source.StatusEncrypted, dek)
		if err != nil {
			errs.Set("Status decryption", err)
		} else {
			err = encx.DeserializeValue(StatusBytes, &result.Status)
			if err != nil {
				errs.Set("Status deserialization", err)
			}
		}
	}
	
	
	// Decrypt UpdatedAt
	if len(source.UpdatedAtEncrypted) > 0 {
		UpdatedAtBytes, err := crypto.DecryptData(ctx, source.UpdatedAtEncrypted, dek)
		if err != nil {
			errs.Set("UpdatedAt decryption", err)
		} else {
			err = encx.DeserializeValue(UpdatedAtBytes, &result.UpdatedAt)
			if err != nil {
				errs.Set("UpdatedAt deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
