// Code generated by encx-gen. DO NOT EDIT.
// Source: case.go
// Generated: 2025-12-29T01:18:08+01:00

package caseDomain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// CaseEncx represents the encrypted version of Case
type CaseEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	ClientID uuid.UUID `db:"clientid" json:"clientid"`
	
	AssignedContactID *uuid.UUID `db:"assignedcontactid" json:"assignedcontactid"`
	
	CaseSubjectID *uuid.UUID `db:"casesubjectid" json:"casesubjectid"`
	
	CaseType string `db:"casetype" json:"casetype"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	TitleEncrypted []byte `db:"title_encrypted" json:"title_encrypted"`
	
	DescriptionEncrypted []byte `db:"description_encrypted" json:"description_encrypted"`
	
	ExternalReferenceEncrypted []byte `db:"externalreference_encrypted" json:"externalreference_encrypted"`
	
	ExternalReferenceHash string `db:"externalreference_hash" json:"externalreference_hash"`
	
	StatusEncrypted []byte `db:"status_encrypted" json:"status_encrypted"`
	
	PlacenameEncrypted []byte `db:"placename_encrypted" json:"placename_encrypted"`
	
	PlacenameHash string `db:"placename_hash" json:"placename_hash"`
	
	Address1Encrypted []byte `db:"address1_encrypted" json:"address1_encrypted"`
	
	Address1Hash string `db:"address1_hash" json:"address1_hash"`
	
	Address2Encrypted []byte `db:"address2_encrypted" json:"address2_encrypted"`
	
	Address2Hash string `db:"address2_hash" json:"address2_hash"`
	
	CityEncrypted []byte `db:"city_encrypted" json:"city_encrypted"`
	
	CityHash string `db:"city_hash" json:"city_hash"`
	
	PostalCodeEncrypted []byte `db:"postalcode_encrypted" json:"postalcode_encrypted"`
	
	PostalCodeHash string `db:"postalcode_hash" json:"postalcode_hash"`
	
	CountryEncrypted []byte `db:"country_encrypted" json:"country_encrypted"`
	
	CountryHash string `db:"country_hash" json:"country_hash"`
	
	LatitudeEncrypted []byte `db:"latitude_encrypted" json:"latitude_encrypted"`
	
	LatitudeHash string `db:"latitude_hash" json:"latitude_hash"`
	
	LongitudeEncrypted []byte `db:"longitude_encrypted" json:"longitude_encrypted"`
	
	LongitudeHash string `db:"longitude_hash" json:"longitude_hash"`
	
	LocationTypeEncrypted []byte `db:"locationtype_encrypted" json:"locationtype_encrypted"`
	
	LocationTypeHash string `db:"locationtype_hash" json:"locationtype_hash"`
	
	LocationNotesEncrypted []byte `db:"locationnotes_encrypted" json:"locationnotes_encrypted"`
	
	LocationNotesHash string `db:"locationnotes_hash" json:"locationnotes_hash"`
	
	UpdatedAtEncrypted []byte `db:"updatedat_encrypted" json:"updatedat_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessCaseEncx encrypts and hashes fields based on encx tags
func ProcessCaseEncx(ctx context.Context, crypto encx.CryptoService, source *Case) (*CaseEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &CaseEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ClientID = source.ClientID
	
	result.AssignedContactID = source.AssignedContactID
	
	result.CaseSubjectID = source.CaseSubjectID
	
	result.CaseType = source.CaseType
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Title (encrypt)
	TitleBytes, err := encx.SerializeValue(source.Title)
	if err != nil {
		errs.Set("Title serialization", err)
	} else {
		result.TitleEncrypted, err = crypto.EncryptData(ctx, TitleBytes, dek)
		if err != nil {
			errs.Set("Title encryption", err)
		}
	}
	
	
	
	// Process Description (encrypt)
	DescriptionBytes, err := encx.SerializeValue(source.Description)
	if err != nil {
		errs.Set("Description serialization", err)
	} else {
		result.DescriptionEncrypted, err = crypto.EncryptData(ctx, DescriptionBytes, dek)
		if err != nil {
			errs.Set("Description encryption", err)
		}
	}
	
	
	
	// Process ExternalReference (encrypt + hash_basic)
	if source.ExternalReference != nil {
	ExternalReferenceBytes, err := encx.SerializeValue(source.ExternalReference)
	if err != nil {
		errs.Set("ExternalReference serialization", err)
	} else {
		result.ExternalReferenceEncrypted, err = crypto.EncryptData(ctx, ExternalReferenceBytes, dek)
		if err != nil {
			errs.Set("ExternalReference encryption", err)
		}
		result.ExternalReferenceHash = crypto.HashBasic(ctx, ExternalReferenceBytes)
		
	}
	}
	
	
	
	// Process Status (encrypt)
	StatusBytes, err := encx.SerializeValue(source.Status)
	if err != nil {
		errs.Set("Status serialization", err)
	} else {
		result.StatusEncrypted, err = crypto.EncryptData(ctx, StatusBytes, dek)
		if err != nil {
			errs.Set("Status encryption", err)
		}
	}
	
	
	
	// Process Placename (encrypt + hash_basic)
	PlacenameBytes, err := encx.SerializeValue(source.Placename)
	if err != nil {
		errs.Set("Placename serialization", err)
	} else {
		result.PlacenameEncrypted, err = crypto.EncryptData(ctx, PlacenameBytes, dek)
		if err != nil {
			errs.Set("Placename encryption", err)
		}
		result.PlacenameHash = crypto.HashBasic(ctx, PlacenameBytes)
		
	}
	
	
	
	// Process Address1 (encrypt + hash_basic)
	Address1Bytes, err := encx.SerializeValue(source.Address1)
	if err != nil {
		errs.Set("Address1 serialization", err)
	} else {
		result.Address1Encrypted, err = crypto.EncryptData(ctx, Address1Bytes, dek)
		if err != nil {
			errs.Set("Address1 encryption", err)
		}
		result.Address1Hash = crypto.HashBasic(ctx, Address1Bytes)
		
	}
	
	
	
	// Process Address2 (encrypt + hash_basic)
	Address2Bytes, err := encx.SerializeValue(source.Address2)
	if err != nil {
		errs.Set("Address2 serialization", err)
	} else {
		result.Address2Encrypted, err = crypto.EncryptData(ctx, Address2Bytes, dek)
		if err != nil {
			errs.Set("Address2 encryption", err)
		}
		result.Address2Hash = crypto.HashBasic(ctx, Address2Bytes)
		
	}
	
	
	
	// Process City (encrypt + hash_basic)
	CityBytes, err := encx.SerializeValue(source.City)
	if err != nil {
		errs.Set("City serialization", err)
	} else {
		result.CityEncrypted, err = crypto.EncryptData(ctx, CityBytes, dek)
		if err != nil {
			errs.Set("City encryption", err)
		}
		result.CityHash = crypto.HashBasic(ctx, CityBytes)
		
	}
	
	
	
	// Process PostalCode (encrypt + hash_basic)
	PostalCodeBytes, err := encx.SerializeValue(source.PostalCode)
	if err != nil {
		errs.Set("PostalCode serialization", err)
	} else {
		result.PostalCodeEncrypted, err = crypto.EncryptData(ctx, PostalCodeBytes, dek)
		if err != nil {
			errs.Set("PostalCode encryption", err)
		}
		result.PostalCodeHash = crypto.HashBasic(ctx, PostalCodeBytes)
		
	}
	
	
	
	// Process Country (encrypt + hash_basic)
	CountryBytes, err := encx.SerializeValue(source.Country)
	if err != nil {
		errs.Set("Country serialization", err)
	} else {
		result.CountryEncrypted, err = crypto.EncryptData(ctx, CountryBytes, dek)
		if err != nil {
			errs.Set("Country encryption", err)
		}
		result.CountryHash = crypto.HashBasic(ctx, CountryBytes)
		
	}
	
	
	
	// Process Latitude (encrypt + hash_basic)
	if source.Latitude != nil {
	LatitudeBytes, err := encx.SerializeValue(source.Latitude)
	if err != nil {
		errs.Set("Latitude serialization", err)
	} else {
		result.LatitudeEncrypted, err = crypto.EncryptData(ctx, LatitudeBytes, dek)
		if err != nil {
			errs.Set("Latitude encryption", err)
		}
		result.LatitudeHash = crypto.HashBasic(ctx, LatitudeBytes)
		
	}
	}
	
	
	
	// Process Longitude (encrypt + hash_basic)
	if source.Longitude != nil {
	LongitudeBytes, err := encx.SerializeValue(source.Longitude)
	if err != nil {
		errs.Set("Longitude serialization", err)
	} else {
		result.LongitudeEncrypted, err = crypto.EncryptData(ctx, LongitudeBytes, dek)
		if err != nil {
			errs.Set("Longitude encryption", err)
		}
		result.LongitudeHash = crypto.HashBasic(ctx, LongitudeBytes)
		
	}
	}
	
	
	
	// Process LocationType (encrypt + hash_basic)
	LocationTypeBytes, err := encx.SerializeValue(source.LocationType)
	if err != nil {
		errs.Set("LocationType serialization", err)
	} else {
		result.LocationTypeEncrypted, err = crypto.EncryptData(ctx, LocationTypeBytes, dek)
		if err != nil {
			errs.Set("LocationType encryption", err)
		}
		result.LocationTypeHash = crypto.HashBasic(ctx, LocationTypeBytes)
		
	}
	
	
	
	// Process LocationNotes (encrypt + hash_basic)
	LocationNotesBytes, err := encx.SerializeValue(source.LocationNotes)
	if err != nil {
		errs.Set("LocationNotes serialization", err)
	} else {
		result.LocationNotesEncrypted, err = crypto.EncryptData(ctx, LocationNotesBytes, dek)
		if err != nil {
			errs.Set("LocationNotes encryption", err)
		}
		result.LocationNotesHash = crypto.HashBasic(ctx, LocationNotesBytes)
		
	}
	
	
	
	// Process UpdatedAt (encrypt)
	if !source.UpdatedAt.IsZero() {
	UpdatedAtBytes, err := encx.SerializeValue(source.UpdatedAt)
	if err != nil {
		errs.Set("UpdatedAt serialization", err)
	} else {
		result.UpdatedAtEncrypted, err = crypto.EncryptData(ctx, UpdatedAtBytes, dek)
		if err != nil {
			errs.Set("UpdatedAt encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptCaseEncx decrypts the encrypted struct back to original
func DecryptCaseEncx(ctx context.Context, crypto encx.CryptoService, source *CaseEncx) (*Case, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Case{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ClientID = source.ClientID
	
	result.AssignedContactID = source.AssignedContactID
	
	result.CaseSubjectID = source.CaseSubjectID
	
	result.CaseType = source.CaseType
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Title
	if len(source.TitleEncrypted) > 0 {
		TitleBytes, err := crypto.DecryptData(ctx, source.TitleEncrypted, dek)
		if err != nil {
			errs.Set("Title decryption", err)
		} else {
			err = encx.DeserializeValue(TitleBytes, &result.Title)
			if err != nil {
				errs.Set("Title deserialization", err)
			}
		}
	}
	
	
	// Decrypt Description
	if len(source.DescriptionEncrypted) > 0 {
		DescriptionBytes, err := crypto.DecryptData(ctx, source.DescriptionEncrypted, dek)
		if err != nil {
			errs.Set("Description decryption", err)
		} else {
			err = encx.DeserializeValue(DescriptionBytes, &result.Description)
			if err != nil {
				errs.Set("Description deserialization", err)
			}
		}
	}
	
	
	// Decrypt ExternalReference
	if len(source.ExternalReferenceEncrypted) > 0 {
		ExternalReferenceBytes, err := crypto.DecryptData(ctx, source.ExternalReferenceEncrypted, dek)
		if err != nil {
			errs.Set("ExternalReference decryption", err)
		} else {
			err = encx.DeserializeValue(ExternalReferenceBytes, &result.ExternalReference)
			if err != nil {
				errs.Set("ExternalReference deserialization", err)
			}
		}
	}
	
	
	// Decrypt Status
	if len(source.StatusEncrypted) > 0 {
		StatusBytes, err := crypto.DecryptData(ctx, source.StatusEncrypted, dek)
		if err != nil {
			errs.Set("Status decryption", err)
		} else {
			err = encx.DeserializeValue(StatusBytes, &result.Status)
			if err != nil {
				errs.Set("Status deserialization", err)
			}
		}
	}
	
	
	// Decrypt Placename
	if len(source.PlacenameEncrypted) > 0 {
		PlacenameBytes, err := crypto.DecryptData(ctx, source.PlacenameEncrypted, dek)
		if err != nil {
			errs.Set("Placename decryption", err)
		} else {
			err = encx.DeserializeValue(PlacenameBytes, &result.Placename)
			if err != nil {
				errs.Set("Placename deserialization", err)
			}
		}
	}
	
	
	// Decrypt Address1
	if len(source.Address1Encrypted) > 0 {
		Address1Bytes, err := crypto.DecryptData(ctx, source.Address1Encrypted, dek)
		if err != nil {
			errs.Set("Address1 decryption", err)
		} else {
			err = encx.DeserializeValue(Address1Bytes, &result.Address1)
			if err != nil {
				errs.Set("Address1 deserialization", err)
			}
		}
	}
	
	
	// Decrypt Address2
	if len(source.Address2Encrypted) > 0 {
		Address2Bytes, err := crypto.DecryptData(ctx, source.Address2Encrypted, dek)
		if err != nil {
			errs.Set("Address2 decryption", err)
		} else {
			err = encx.DeserializeValue(Address2Bytes, &result.Address2)
			if err != nil {
				errs.Set("Address2 deserialization", err)
			}
		}
	}
	
	
	// Decrypt City
	if len(source.CityEncrypted) > 0 {
		CityBytes, err := crypto.DecryptData(ctx, source.CityEncrypted, dek)
		if err != nil {
			errs.Set("City decryption", err)
		} else {
			err = encx.DeserializeValue(CityBytes, &result.City)
			if err != nil {
				errs.Set("City deserialization", err)
			}
		}
	}
	
	
	// Decrypt PostalCode
	if len(source.PostalCodeEncrypted) > 0 {
		PostalCodeBytes, err := crypto.DecryptData(ctx, source.PostalCodeEncrypted, dek)
		if err != nil {
			errs.Set("PostalCode decryption", err)
		} else {
			err = encx.DeserializeValue(PostalCodeBytes, &result.PostalCode)
			if err != nil {
				errs.Set("PostalCode deserialization", err)
			}
		}
	}
	
	
	// Decrypt Country
	if len(source.CountryEncrypted) > 0 {
		CountryBytes, err := crypto.DecryptData(ctx, source.CountryEncrypted, dek)
		if err != nil {
			errs.Set("Country decryption", err)
		} else {
			err = encx.DeserializeValue(CountryBytes, &result.Country)
			if err != nil {
				errs.Set("Country deserialization", err)
			}
		}
	}
	
	
	// Decrypt Latitude
	if len(source.LatitudeEncrypted) > 0 {
		LatitudeBytes, err := crypto.DecryptData(ctx, source.LatitudeEncrypted, dek)
		if err != nil {
			errs.Set("Latitude decryption", err)
		} else {
			err = encx.DeserializeValue(LatitudeBytes, &result.Latitude)
			if err != nil {
				errs.Set("Latitude deserialization", err)
			}
		}
	}
	
	
	// Decrypt Longitude
	if len(source.LongitudeEncrypted) > 0 {
		LongitudeBytes, err := crypto.DecryptData(ctx, source.LongitudeEncrypted, dek)
		if err != nil {
			errs.Set("Longitude decryption", err)
		} else {
			err = encx.DeserializeValue(LongitudeBytes, &result.Longitude)
			if err != nil {
				errs.Set("Longitude deserialization", err)
			}
		}
	}
	
	
	// Decrypt LocationType
	if len(source.LocationTypeEncrypted) > 0 {
		LocationTypeBytes, err := crypto.DecryptData(ctx, source.LocationTypeEncrypted, dek)
		if err != nil {
			errs.Set("LocationType decryption", err)
		} else {
			err = encx.DeserializeValue(LocationTypeBytes, &result.LocationType)
			if err != nil {
				errs.Set("LocationType deserialization", err)
			}
		}
	}
	
	
	// Decrypt LocationNotes
	if len(source.LocationNotesEncrypted) > 0 {
		LocationNotesBytes, err := crypto.DecryptData(ctx, source.LocationNotesEncrypted, dek)
		if err != nil {
			errs.Set("LocationNotes decryption", err)
		} else {
			err = encx.DeserializeValue(LocationNotesBytes, &result.LocationNotes)
			if err != nil {
				errs.Set("LocationNotes deserialization", err)
			}
		}
	}
	
	
	// Decrypt UpdatedAt
	if len(source.UpdatedAtEncrypted) > 0 {
		UpdatedAtBytes, err := crypto.DecryptData(ctx, source.UpdatedAtEncrypted, dek)
		if err != nil {
			errs.Set("UpdatedAt decryption", err)
		} else {
			err = encx.DeserializeValue(UpdatedAtBytes, &result.UpdatedAt)
			if err != nil {
				errs.Set("UpdatedAt deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
