// Code generated by encx-gen. DO NOT EDIT.
// Source: chat_conversation.go
// Generated: 2026-02-01T22:55:57+01:00

package ai

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// ChatConversationEncx represents the encrypted version of ChatConversation
type ChatConversationEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	CaseID uuid.UUID `db:"caseid" json:"caseid"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	CreatedBy uuid.UUID `db:"createdby" json:"createdby"`
	
	MessageCount int `db:"messagecount" json:"messagecount"`
	
	TotalTokens int `db:"totaltokens" json:"totaltokens"`
	
	
	TitleEncrypted []byte `db:"title_encrypted" json:"title_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessChatConversationEncx encrypts and hashes fields based on encx tags
func ProcessChatConversationEncx(ctx context.Context, crypto encx.CryptoService, source *ChatConversation) (*ChatConversationEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &ChatConversationEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.CaseID = source.CaseID
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.CreatedBy = source.CreatedBy
	
	result.MessageCount = source.MessageCount
	
	result.TotalTokens = source.TotalTokens
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Title (encrypt)
	TitleBytes, err := encx.SerializeValue(source.Title)
	if err != nil {
		errs.Set("Title serialization", err)
	} else {
		result.TitleEncrypted, err = crypto.EncryptData(ctx, TitleBytes, dek)
		if err != nil {
			errs.Set("Title encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptChatConversationEncx decrypts the encrypted struct back to original
func DecryptChatConversationEncx(ctx context.Context, crypto encx.CryptoService, source *ChatConversationEncx) (*ChatConversation, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &ChatConversation{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.CaseID = source.CaseID
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.CreatedBy = source.CreatedBy
	
	result.MessageCount = source.MessageCount
	
	result.TotalTokens = source.TotalTokens
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Title
	if len(source.TitleEncrypted) > 0 {
		TitleBytes, err := crypto.DecryptData(ctx, source.TitleEncrypted, dek)
		if err != nil {
			errs.Set("Title decryption", err)
		} else {
			err = encx.DeserializeValue(TitleBytes, &result.Title)
			if err != nil {
				errs.Set("Title deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
