// Code generated by encx-gen. DO NOT EDIT.
// Source: chat_message.go
// Generated: 2026-02-01T22:55:57+01:00

package ai

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// ChatMessageEncx represents the encrypted version of ChatMessage
type ChatMessageEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	ConversationID uuid.UUID `db:"conversationid" json:"conversationid"`
	
	Role ChatRole `db:"role" json:"role"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	TokenCount int `db:"tokencount" json:"tokencount"`
	
	
	ContentEncrypted []byte `db:"content_encrypted" json:"content_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessChatMessageEncx encrypts and hashes fields based on encx tags
func ProcessChatMessageEncx(ctx context.Context, crypto encx.CryptoService, source *ChatMessage) (*ChatMessageEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &ChatMessageEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ConversationID = source.ConversationID
	
	result.Role = source.Role
	
	result.CreatedAt = source.CreatedAt
	
	result.TokenCount = source.TokenCount
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Content (encrypt)
	ContentBytes, err := encx.SerializeValue(source.Content)
	if err != nil {
		errs.Set("Content serialization", err)
	} else {
		result.ContentEncrypted, err = crypto.EncryptData(ctx, ContentBytes, dek)
		if err != nil {
			errs.Set("Content encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptChatMessageEncx decrypts the encrypted struct back to original
func DecryptChatMessageEncx(ctx context.Context, crypto encx.CryptoService, source *ChatMessageEncx) (*ChatMessage, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &ChatMessage{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ConversationID = source.ConversationID
	
	result.Role = source.Role
	
	result.CreatedAt = source.CreatedAt
	
	result.TokenCount = source.TokenCount
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Content
	if len(source.ContentEncrypted) > 0 {
		ContentBytes, err := crypto.DecryptData(ctx, source.ContentEncrypted, dek)
		if err != nil {
			errs.Set("Content decryption", err)
		} else {
			err = encx.DeserializeValue(ContentBytes, &result.Content)
			if err != nil {
				errs.Set("Content deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
