// Code generated by encx-gen. DO NOT EDIT.
// Source: speech_to_text.go
// Generated: 2026-01-30T19:02:18+01:00

package ai

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// TranscriptionEncx represents the encrypted version of Transcription
type TranscriptionEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	JobID uuid.UUID `db:"jobid" json:"jobid"`
	
	MediaFileID uuid.UUID `db:"mediafileid" json:"mediafileid"`
	
	AudioURL string `db:"audiourl" json:"audiourl"`
	
	ConfidenceScore float32 `db:"confidencescore" json:"confidencescore"`
	
	Language string `db:"language" json:"language"`
	
	Duration int64 `db:"duration" json:"duration"`
	
	ModelName string `db:"modelname" json:"modelname"`
	
	ProcessingTimeMs int64 `db:"processingtimems" json:"processingtimems"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	AudioDeletedAt *time.Time `db:"audiodeletedat" json:"audiodeletedat"`
	
	
	TranscriptEncrypted []byte `db:"transcript_encrypted" json:"transcript_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessTranscriptionEncx encrypts and hashes fields based on encx tags
func ProcessTranscriptionEncx(ctx context.Context, crypto encx.CryptoService, source *Transcription) (*TranscriptionEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &TranscriptionEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.JobID = source.JobID
	
	result.MediaFileID = source.MediaFileID
	
	result.AudioURL = source.AudioURL
	
	result.ConfidenceScore = source.ConfidenceScore
	
	result.Language = source.Language
	
	result.Duration = source.Duration
	
	result.ModelName = source.ModelName
	
	result.ProcessingTimeMs = source.ProcessingTimeMs
	
	result.CreatedAt = source.CreatedAt
	
	result.AudioDeletedAt = source.AudioDeletedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Transcript (encrypt)
	TranscriptBytes, err := encx.SerializeValue(source.Transcript)
	if err != nil {
		errs.Set("Transcript serialization", err)
	} else {
		result.TranscriptEncrypted, err = crypto.EncryptData(ctx, TranscriptBytes, dek)
		if err != nil {
			errs.Set("Transcript encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptTranscriptionEncx decrypts the encrypted struct back to original
func DecryptTranscriptionEncx(ctx context.Context, crypto encx.CryptoService, source *TranscriptionEncx) (*Transcription, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Transcription{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.JobID = source.JobID
	
	result.MediaFileID = source.MediaFileID
	
	result.AudioURL = source.AudioURL
	
	result.ConfidenceScore = source.ConfidenceScore
	
	result.Language = source.Language
	
	result.Duration = source.Duration
	
	result.ModelName = source.ModelName
	
	result.ProcessingTimeMs = source.ProcessingTimeMs
	
	result.CreatedAt = source.CreatedAt
	
	result.AudioDeletedAt = source.AudioDeletedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Transcript
	if len(source.TranscriptEncrypted) > 0 {
		TranscriptBytes, err := crypto.DecryptData(ctx, source.TranscriptEncrypted, dek)
		if err != nil {
			errs.Set("Transcript decryption", err)
		} else {
			err = encx.DeserializeValue(TranscriptBytes, &result.Transcript)
			if err != nil {
				errs.Set("Transcript deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
