// Code generated by encx-gen. DO NOT EDIT.
// Source: text_transformation.go
// Generated: 2026-01-30T19:02:18+01:00

package ai

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// TextTransformationEncx represents the encrypted version of TextTransformation
type TextTransformationEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	TransformationType TextTransformationType `db:"transformationtype" json:"transformationtype"`
	
	ModelUsed string `db:"modelused" json:"modelused"`
	
	InputLength int `db:"inputlength" json:"inputlength"`
	
	OutputLength int `db:"outputlength" json:"outputlength"`
	
	ProcessingTimeMs int64 `db:"processingtimems" json:"processingtimems"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	InputTextEncrypted []byte `db:"inputtext_encrypted" json:"inputtext_encrypted"`
	
	OutputTextEncrypted []byte `db:"outputtext_encrypted" json:"outputtext_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessTextTransformationEncx encrypts and hashes fields based on encx tags
func ProcessTextTransformationEncx(ctx context.Context, crypto encx.CryptoService, source *TextTransformation) (*TextTransformationEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &TextTransformationEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.TransformationType = source.TransformationType
	
	result.ModelUsed = source.ModelUsed
	
	result.InputLength = source.InputLength
	
	result.OutputLength = source.OutputLength
	
	result.ProcessingTimeMs = source.ProcessingTimeMs
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process InputText (encrypt)
	InputTextBytes, err := encx.SerializeValue(source.InputText)
	if err != nil {
		errs.Set("InputText serialization", err)
	} else {
		result.InputTextEncrypted, err = crypto.EncryptData(ctx, InputTextBytes, dek)
		if err != nil {
			errs.Set("InputText encryption", err)
		}
	}
	
	
	
	// Process OutputText (encrypt)
	OutputTextBytes, err := encx.SerializeValue(source.OutputText)
	if err != nil {
		errs.Set("OutputText serialization", err)
	} else {
		result.OutputTextEncrypted, err = crypto.EncryptData(ctx, OutputTextBytes, dek)
		if err != nil {
			errs.Set("OutputText encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptTextTransformationEncx decrypts the encrypted struct back to original
func DecryptTextTransformationEncx(ctx context.Context, crypto encx.CryptoService, source *TextTransformationEncx) (*TextTransformation, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &TextTransformation{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.TransformationType = source.TransformationType
	
	result.ModelUsed = source.ModelUsed
	
	result.InputLength = source.InputLength
	
	result.OutputLength = source.OutputLength
	
	result.ProcessingTimeMs = source.ProcessingTimeMs
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt InputText
	if len(source.InputTextEncrypted) > 0 {
		InputTextBytes, err := crypto.DecryptData(ctx, source.InputTextEncrypted, dek)
		if err != nil {
			errs.Set("InputText decryption", err)
		} else {
			err = encx.DeserializeValue(InputTextBytes, &result.InputText)
			if err != nil {
				errs.Set("InputText deserialization", err)
			}
		}
	}
	
	
	// Decrypt OutputText
	if len(source.OutputTextEncrypted) > 0 {
		OutputTextBytes, err := crypto.DecryptData(ctx, source.OutputTextEncrypted, dek)
		if err != nil {
			errs.Set("OutputText decryption", err)
		} else {
			err = encx.DeserializeValue(OutputTextBytes, &result.OutputText)
			if err != nil {
				errs.Set("OutputText deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
