// Code generated by encx-gen. DO NOT EDIT.
// Source: transcript_analysis.go
// Generated: 2026-01-30T19:02:18+01:00

package ai

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// TranscriptAnalysisEncx represents the encrypted version of TranscriptAnalysis
type TranscriptAnalysisEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	TranscriptionID uuid.UUID `db:"transcriptionid" json:"transcriptionid"`
	
	Sentiment string `db:"sentiment" json:"sentiment"`
	
	ModelUsed string `db:"modelused" json:"modelused"`
	
	ProcessingTimeMs int64 `db:"processingtimems" json:"processingtimems"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	KeyFindingsEncrypted []byte `db:"keyfindings_encrypted" json:"keyfindings_encrypted"`
	
	SummaryEncrypted []byte `db:"summary_encrypted" json:"summary_encrypted"`
	
	TopicsEncrypted []byte `db:"topics_encrypted" json:"topics_encrypted"`
	
	SuggestedActionsEncrypted []byte `db:"suggestedactions_encrypted" json:"suggestedactions_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessTranscriptAnalysisEncx encrypts and hashes fields based on encx tags
func ProcessTranscriptAnalysisEncx(ctx context.Context, crypto encx.CryptoService, source *TranscriptAnalysis) (*TranscriptAnalysisEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &TranscriptAnalysisEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.TranscriptionID = source.TranscriptionID
	
	result.Sentiment = source.Sentiment
	
	result.ModelUsed = source.ModelUsed
	
	result.ProcessingTimeMs = source.ProcessingTimeMs
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process KeyFindings (encrypt)
	KeyFindingsBytes, err := encx.SerializeValue(source.KeyFindings)
	if err != nil {
		errs.Set("KeyFindings serialization", err)
	} else {
		result.KeyFindingsEncrypted, err = crypto.EncryptData(ctx, KeyFindingsBytes, dek)
		if err != nil {
			errs.Set("KeyFindings encryption", err)
		}
	}
	
	
	
	// Process Summary (encrypt)
	SummaryBytes, err := encx.SerializeValue(source.Summary)
	if err != nil {
		errs.Set("Summary serialization", err)
	} else {
		result.SummaryEncrypted, err = crypto.EncryptData(ctx, SummaryBytes, dek)
		if err != nil {
			errs.Set("Summary encryption", err)
		}
	}
	
	
	
	// Process Topics (encrypt)
	TopicsBytes, err := encx.SerializeValue(source.Topics)
	if err != nil {
		errs.Set("Topics serialization", err)
	} else {
		result.TopicsEncrypted, err = crypto.EncryptData(ctx, TopicsBytes, dek)
		if err != nil {
			errs.Set("Topics encryption", err)
		}
	}
	
	
	
	// Process SuggestedActions (encrypt)
	SuggestedActionsBytes, err := encx.SerializeValue(source.SuggestedActions)
	if err != nil {
		errs.Set("SuggestedActions serialization", err)
	} else {
		result.SuggestedActionsEncrypted, err = crypto.EncryptData(ctx, SuggestedActionsBytes, dek)
		if err != nil {
			errs.Set("SuggestedActions encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptTranscriptAnalysisEncx decrypts the encrypted struct back to original
func DecryptTranscriptAnalysisEncx(ctx context.Context, crypto encx.CryptoService, source *TranscriptAnalysisEncx) (*TranscriptAnalysis, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &TranscriptAnalysis{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.TranscriptionID = source.TranscriptionID
	
	result.Sentiment = source.Sentiment
	
	result.ModelUsed = source.ModelUsed
	
	result.ProcessingTimeMs = source.ProcessingTimeMs
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt KeyFindings
	if len(source.KeyFindingsEncrypted) > 0 {
		KeyFindingsBytes, err := crypto.DecryptData(ctx, source.KeyFindingsEncrypted, dek)
		if err != nil {
			errs.Set("KeyFindings decryption", err)
		} else {
			err = encx.DeserializeValue(KeyFindingsBytes, &result.KeyFindings)
			if err != nil {
				errs.Set("KeyFindings deserialization", err)
			}
		}
	}
	
	
	// Decrypt Summary
	if len(source.SummaryEncrypted) > 0 {
		SummaryBytes, err := crypto.DecryptData(ctx, source.SummaryEncrypted, dek)
		if err != nil {
			errs.Set("Summary decryption", err)
		} else {
			err = encx.DeserializeValue(SummaryBytes, &result.Summary)
			if err != nil {
				errs.Set("Summary deserialization", err)
			}
		}
	}
	
	
	// Decrypt Topics
	if len(source.TopicsEncrypted) > 0 {
		TopicsBytes, err := crypto.DecryptData(ctx, source.TopicsEncrypted, dek)
		if err != nil {
			errs.Set("Topics decryption", err)
		} else {
			err = encx.DeserializeValue(TopicsBytes, &result.Topics)
			if err != nil {
				errs.Set("Topics deserialization", err)
			}
		}
	}
	
	
	// Decrypt SuggestedActions
	if len(source.SuggestedActionsEncrypted) > 0 {
		SuggestedActionsBytes, err := crypto.DecryptData(ctx, source.SuggestedActionsEncrypted, dek)
		if err != nil {
			errs.Set("SuggestedActions decryption", err)
		} else {
			err = encx.DeserializeValue(SuggestedActionsBytes, &result.SuggestedActions)
			if err != nil {
				errs.Set("SuggestedActions deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
