// Code generated by encx-gen. DO NOT EDIT.
// Source: client.go
// Generated: 2025-12-02T20:43:16+01:00

package client

import (
	"context"
	"time"

	"github.com/hengadev/encx"
	"github.com/hengadev/errsx"

	"github.com/google/uuid"
)

// ClientEncx represents the encrypted version of Client
type ClientEncx struct {
	ID uuid.UUID `db:"id" json:"id"`

	CreatedAt time.Time `db:"createdat" json:"createdat"`

	NameEncrypted []byte `db:"name_encrypted" json:"name_encrypted"`

	NameHash string `db:"name_hash" json:"name_hash"`

	TypeEncrypted []byte `db:"type_encrypted" json:"type_encrypted"`

	TypeHash string `db:"type_hash" json:"type_hash"`

	ContactIDsEncrypted []byte `db:"contactids_encrypted" json:"contactids_encrypted"`

	// Essential encryption fields
	DEKEncrypted []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion   int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessClientEncx encrypts and hashes fields based on encx tags
func ProcessClientEncx(ctx context.Context, crypto encx.CryptoService, source *Client) (*ClientEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &ClientEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)

	result.ID = source.ID

	result.CreatedAt = source.CreatedAt

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	// Process Name (encrypt + hash_basic)
	NameBytes, err := encx.SerializeValue(source.Name)
	if err != nil {
		errs.Set("Name serialization", err)
	} else {
		result.NameEncrypted, err = crypto.EncryptData(ctx, NameBytes, dek)
		if err != nil {
			errs.Set("Name encryption", err)
		}
		result.NameHash = crypto.HashBasic(ctx, NameBytes)

	}

	// Process Type (encrypt + hash_basic)
	TypeBytes, err := encx.SerializeValue(source.Type)
	if err != nil {
		errs.Set("Type serialization", err)
	} else {
		result.TypeEncrypted, err = crypto.EncryptData(ctx, TypeBytes, dek)
		if err != nil {
			errs.Set("Type encryption", err)
		}
		result.TypeHash = crypto.HashBasic(ctx, TypeBytes)

	}

	// Process ContactIDs (encrypt)
	ContactIDsBytes, err := encx.SerializeValue(source.ContactIDs)
	if err != nil {
		errs.Set("ContactIDs serialization", err)
	} else {
		result.ContactIDsEncrypted, err = crypto.EncryptData(ctx, ContactIDsBytes, dek)
		if err != nil {
			errs.Set("ContactIDs encryption", err)
		}
	}

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptClientEncx decrypts the encrypted struct back to original
func DecryptClientEncx(ctx context.Context, crypto encx.CryptoService, source *ClientEncx) (*Client, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Client{}

	// Copy plain fields (non-encx fields)

	result.ID = source.ID

	result.CreatedAt = source.CreatedAt

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	// Decrypt Name
	if len(source.NameEncrypted) > 0 {
		NameBytes, err := crypto.DecryptData(ctx, source.NameEncrypted, dek)
		if err != nil {
			errs.Set("Name decryption", err)
		} else {
			err = encx.DeserializeValue(NameBytes, &result.Name)
			if err != nil {
				errs.Set("Name deserialization", err)
			}
		}
	}

	// Decrypt Type
	if len(source.TypeEncrypted) > 0 {
		TypeBytes, err := crypto.DecryptData(ctx, source.TypeEncrypted, dek)
		if err != nil {
			errs.Set("Type decryption", err)
		} else {
			err = encx.DeserializeValue(TypeBytes, &result.Type)
			if err != nil {
				errs.Set("Type deserialization", err)
			}
		}
	}

	// Decrypt ContactIDs
	if len(source.ContactIDsEncrypted) > 0 {
		ContactIDsBytes, err := crypto.DecryptData(ctx, source.ContactIDsEncrypted, dek)
		if err != nil {
			errs.Set("ContactIDs decryption", err)
		} else {
			err = encx.DeserializeValue(ContactIDsBytes, &result.ContactIDs)
			if err != nil {
				errs.Set("ContactIDs deserialization", err)
			}
		}
	}

	return result, errs.AsError()
}
