// Code generated by encx-gen. DO NOT EDIT.
// Source: contact.go
// Generated: 2025-12-03T17:43:36+01:00

package client

import (
	"context"
	"time"

	"github.com/hengadev/encx"
	"github.com/hengadev/errsx"

	"github.com/google/uuid"
)

// ContactEncx represents the encrypted version of Contact
type ContactEncx struct {
	ID uuid.UUID `db:"id" json:"id"`

	ClientID uuid.UUID `db:"clientid" json:"clientid"`

	CreatedAt time.Time `db:"createdat" json:"createdat"`

	LastnameEncrypted []byte `db:"lastname_encrypted" json:"lastname_encrypted"`

	FirstnameEncrypted []byte `db:"firstname_encrypted" json:"firstname_encrypted"`

	EmailEncrypted []byte `db:"email_encrypted" json:"email_encrypted"`

	EmailHash string `db:"email_hash" json:"email_hash"`

	PhoneEncrypted []byte `db:"phone_encrypted" json:"phone_encrypted"`

	PositionEncrypted []byte `db:"position_encrypted" json:"position_encrypted"`

	// Essential encryption fields
	DEKEncrypted []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion   int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessContactEncx encrypts and hashes fields based on encx tags
func ProcessContactEncx(ctx context.Context, crypto encx.CryptoService, source *Contact) (*ContactEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &ContactEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)

	result.ID = source.ID

	result.ClientID = source.ClientID

	result.CreatedAt = source.CreatedAt

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	// Process Lastname (encrypt)
	LastnameBytes, err := encx.SerializeValue(source.Lastname)
	if err != nil {
		errs.Set("Lastname serialization", err)
	} else {
		result.LastnameEncrypted, err = crypto.EncryptData(ctx, LastnameBytes, dek)
		if err != nil {
			errs.Set("Lastname encryption", err)
		}
	}

	// Process Firstname (encrypt)
	FirstnameBytes, err := encx.SerializeValue(source.Firstname)
	if err != nil {
		errs.Set("Firstname serialization", err)
	} else {
		result.FirstnameEncrypted, err = crypto.EncryptData(ctx, FirstnameBytes, dek)
		if err != nil {
			errs.Set("Firstname encryption", err)
		}
	}

	// Process Email (encrypt + hash_basic)
	EmailBytes, err := encx.SerializeValue(source.Email)
	if err != nil {
		errs.Set("Email serialization", err)
	} else {
		result.EmailEncrypted, err = crypto.EncryptData(ctx, EmailBytes, dek)
		if err != nil {
			errs.Set("Email encryption", err)
		}
		result.EmailHash = crypto.HashBasic(ctx, EmailBytes)

	}

	// Process Phone (encrypt)
	PhoneBytes, err := encx.SerializeValue(source.Phone)
	if err != nil {
		errs.Set("Phone serialization", err)
	} else {
		result.PhoneEncrypted, err = crypto.EncryptData(ctx, PhoneBytes, dek)
		if err != nil {
			errs.Set("Phone encryption", err)
		}
	}

	// Process Position (encrypt)
	PositionBytes, err := encx.SerializeValue(source.Position)
	if err != nil {
		errs.Set("Position serialization", err)
	} else {
		result.PositionEncrypted, err = crypto.EncryptData(ctx, PositionBytes, dek)
		if err != nil {
			errs.Set("Position encryption", err)
		}
	}

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptContactEncx decrypts the encrypted struct back to original
func DecryptContactEncx(ctx context.Context, crypto encx.CryptoService, source *ContactEncx) (*Contact, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Contact{}

	// Copy plain fields (non-encx fields)

	result.ID = source.ID

	result.ClientID = source.ClientID

	result.CreatedAt = source.CreatedAt

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	// Decrypt Lastname
	if len(source.LastnameEncrypted) > 0 {
		LastnameBytes, err := crypto.DecryptData(ctx, source.LastnameEncrypted, dek)
		if err != nil {
			errs.Set("Lastname decryption", err)
		} else {
			err = encx.DeserializeValue(LastnameBytes, &result.Lastname)
			if err != nil {
				errs.Set("Lastname deserialization", err)
			}
		}
	}

	// Decrypt Firstname
	if len(source.FirstnameEncrypted) > 0 {
		FirstnameBytes, err := crypto.DecryptData(ctx, source.FirstnameEncrypted, dek)
		if err != nil {
			errs.Set("Firstname decryption", err)
		} else {
			err = encx.DeserializeValue(FirstnameBytes, &result.Firstname)
			if err != nil {
				errs.Set("Firstname deserialization", err)
			}
		}
	}

	// Decrypt Email
	if len(source.EmailEncrypted) > 0 {
		EmailBytes, err := crypto.DecryptData(ctx, source.EmailEncrypted, dek)
		if err != nil {
			errs.Set("Email decryption", err)
		} else {
			err = encx.DeserializeValue(EmailBytes, &result.Email)
			if err != nil {
				errs.Set("Email deserialization", err)
			}
		}
	}

	// Decrypt Phone
	if len(source.PhoneEncrypted) > 0 {
		PhoneBytes, err := crypto.DecryptData(ctx, source.PhoneEncrypted, dek)
		if err != nil {
			errs.Set("Phone decryption", err)
		} else {
			err = encx.DeserializeValue(PhoneBytes, &result.Phone)
			if err != nil {
				errs.Set("Phone deserialization", err)
			}
		}
	}

	// Decrypt Position
	if len(source.PositionEncrypted) > 0 {
		PositionBytes, err := crypto.DecryptData(ctx, source.PositionEncrypted, dek)
		if err != nil {
			errs.Set("Position decryption", err)
		} else {
			err = encx.DeserializeValue(PositionBytes, &result.Position)
			if err != nil {
				errs.Set("Position deserialization", err)
			}
		}
	}

	return result, errs.AsError()
}
