// Code generated by encx-gen. DO NOT EDIT.
// Source: session.go
// Generated: 2025-12-12T07:30:56+01:00

package session

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
	"github.com/hengadev/cluo_api/internal/common/contracts/identity"
	
)

// SessionEncx represents the encrypted version of Session
type SessionEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	
	UserIDEncrypted []byte `db:"userid_encrypted" json:"userid_encrypted"`
	
	UserIDHash string `db:"userid_hash" json:"userid_hash"`
	
	RoleEncrypted []byte `db:"role_encrypted" json:"role_encrypted"`
	
	StateEncrypted []byte `db:"state_encrypted" json:"state_encrypted"`
	
	CreatedAtEncrypted []byte `db:"createdat_encrypted" json:"createdat_encrypted"`
	
	ExpiresAtEncrypted []byte `db:"expiresat_encrypted" json:"expiresat_encrypted"`
	
	CompletedAtEncrypted []byte `db:"completedat_encrypted" json:"completedat_encrypted"`
	
	AccessTokenHash string `db:"accesstoken_hash" json:"accesstoken_hash"`
	
	RefreshTokenHash string `db:"refreshtoken_hash" json:"refreshtoken_hash"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessSessionEncx encrypts and hashes fields based on encx tags
func ProcessSessionEncx(ctx context.Context, crypto encx.CryptoService, source *Session) (*SessionEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &SessionEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process UserID (encrypt + hash_basic)
	if source.UserID != uuid.Nil {
	UserIDBytes, err := encx.SerializeValue(source.UserID)
	if err != nil {
		errs.Set("UserID serialization", err)
	} else {
		result.UserIDEncrypted, err = crypto.EncryptData(ctx, UserIDBytes, dek)
		if err != nil {
			errs.Set("UserID encryption", err)
		}
		result.UserIDHash = crypto.HashBasic(ctx, UserIDBytes)
		
	}
	}
	
	
	
	// Process Role (encrypt)
	RoleBytes, err := encx.SerializeValue(source.Role)
	if err != nil {
		errs.Set("Role serialization", err)
	} else {
		result.RoleEncrypted, err = crypto.EncryptData(ctx, RoleBytes, dek)
		if err != nil {
			errs.Set("Role encryption", err)
		}
	}
	
	
	
	// Process State (encrypt)
	StateBytes, err := encx.SerializeValue(source.State)
	if err != nil {
		errs.Set("State serialization", err)
	} else {
		result.StateEncrypted, err = crypto.EncryptData(ctx, StateBytes, dek)
		if err != nil {
			errs.Set("State encryption", err)
		}
	}
	
	
	
	// Process CreatedAt (encrypt)
	if !source.CreatedAt.IsZero() {
	CreatedAtBytes, err := encx.SerializeValue(source.CreatedAt)
	if err != nil {
		errs.Set("CreatedAt serialization", err)
	} else {
		result.CreatedAtEncrypted, err = crypto.EncryptData(ctx, CreatedAtBytes, dek)
		if err != nil {
			errs.Set("CreatedAt encryption", err)
		}
	}
	}
	
	
	
	// Process ExpiresAt (encrypt)
	if !source.ExpiresAt.IsZero() {
	ExpiresAtBytes, err := encx.SerializeValue(source.ExpiresAt)
	if err != nil {
		errs.Set("ExpiresAt serialization", err)
	} else {
		result.ExpiresAtEncrypted, err = crypto.EncryptData(ctx, ExpiresAtBytes, dek)
		if err != nil {
			errs.Set("ExpiresAt encryption", err)
		}
	}
	}
	
	
	
	// Process CompletedAt (encrypt)
	if source.CompletedAt != nil {
	CompletedAtBytes, err := encx.SerializeValue(source.CompletedAt)
	if err != nil {
		errs.Set("CompletedAt serialization", err)
	} else {
		result.CompletedAtEncrypted, err = crypto.EncryptData(ctx, CompletedAtBytes, dek)
		if err != nil {
			errs.Set("CompletedAt encryption", err)
		}
	}
	}
	
	
	
	// Process AccessToken (hash_basic)
	AccessTokenBytes, err := encx.SerializeValue(source.AccessToken)
	if err != nil {
		errs.Set("AccessToken serialization", err)
	} else {
		result.AccessTokenHash = crypto.HashBasic(ctx, AccessTokenBytes)
	}
	
	
	
	// Process RefreshToken (hash_basic)
	RefreshTokenBytes, err := encx.SerializeValue(source.RefreshToken)
	if err != nil {
		errs.Set("RefreshToken serialization", err)
	} else {
		result.RefreshTokenHash = crypto.HashBasic(ctx, RefreshTokenBytes)
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptSessionEncx decrypts the encrypted struct back to original
func DecryptSessionEncx(ctx context.Context, crypto encx.CryptoService, source *SessionEncx) (*Session, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Session{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt UserID
	if len(source.UserIDEncrypted) > 0 {
		UserIDBytes, err := crypto.DecryptData(ctx, source.UserIDEncrypted, dek)
		if err != nil {
			errs.Set("UserID decryption", err)
		} else {
			err = encx.DeserializeValue(UserIDBytes, &result.UserID)
			if err != nil {
				errs.Set("UserID deserialization", err)
			}
		}
	}
	
	
	// Decrypt Role
	if len(source.RoleEncrypted) > 0 {
		RoleBytes, err := crypto.DecryptData(ctx, source.RoleEncrypted, dek)
		if err != nil {
			errs.Set("Role decryption", err)
		} else {
			err = encx.DeserializeValue(RoleBytes, &result.Role)
			if err != nil {
				errs.Set("Role deserialization", err)
			}
		}
	}
	
	
	// Decrypt State
	if len(source.StateEncrypted) > 0 {
		StateBytes, err := crypto.DecryptData(ctx, source.StateEncrypted, dek)
		if err != nil {
			errs.Set("State decryption", err)
		} else {
			err = encx.DeserializeValue(StateBytes, &result.State)
			if err != nil {
				errs.Set("State deserialization", err)
			}
		}
	}
	
	
	// Decrypt CreatedAt
	if len(source.CreatedAtEncrypted) > 0 {
		CreatedAtBytes, err := crypto.DecryptData(ctx, source.CreatedAtEncrypted, dek)
		if err != nil {
			errs.Set("CreatedAt decryption", err)
		} else {
			err = encx.DeserializeValue(CreatedAtBytes, &result.CreatedAt)
			if err != nil {
				errs.Set("CreatedAt deserialization", err)
			}
		}
	}
	
	
	// Decrypt ExpiresAt
	if len(source.ExpiresAtEncrypted) > 0 {
		ExpiresAtBytes, err := crypto.DecryptData(ctx, source.ExpiresAtEncrypted, dek)
		if err != nil {
			errs.Set("ExpiresAt decryption", err)
		} else {
			err = encx.DeserializeValue(ExpiresAtBytes, &result.ExpiresAt)
			if err != nil {
				errs.Set("ExpiresAt deserialization", err)
			}
		}
	}
	
	
	// Decrypt CompletedAt
	if len(source.CompletedAtEncrypted) > 0 {
		CompletedAtBytes, err := crypto.DecryptData(ctx, source.CompletedAtEncrypted, dek)
		if err != nil {
			errs.Set("CompletedAt decryption", err)
		} else {
			err = encx.DeserializeValue(CompletedAtBytes, &result.CompletedAt)
			if err != nil {
				errs.Set("CompletedAt deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
