# =============================================================================
# AWS SES (Simple Email Service)
# Domain identity + DKIM for transactional emails
# =============================================================================

# =============================================================================
# SES Domain Identity
# =============================================================================

resource "aws_ses_domain_identity" "main" {
  domain = var.domain_name
}

# =============================================================================
# SES DKIM Verification
# =============================================================================

resource "aws_ses_domain_dkim" "main" {
  domain = aws_ses_domain_identity.main.domain
}

# =============================================================================
# SES Domain Mail From
# =============================================================================

resource "aws_ses_domain_mail_from" "main" {
  domain           = aws_ses_domain_identity.main.domain
  mail_from_domain = "mail.${var.domain_name}"
}

# =============================================================================
# Output DKIM tokens for DNS verification
# (See outputs.tf for exposed values)
# =============================================================================

# Note: The DKIM tokens are automatically generated by AWS and need to be
# added to DNS as CNAME records. See cloudflare.tf for the DNS configuration.

# DNS records required:
# 1. Domain verification: _amazonses.${domain_name} TXT <verification_token>
# 2. DKIM tokens (3): ${token1}._domainkey CNAME ${token1}.dkim.amazonses.com
#                     ${token2}._domainkey CNAME ${token2}.dkim.amazonses.com
#                     ${token3}._domainkey CNAME ${token3}.dkim.amazonses.com
# 3. Mail From MX records (optional, for bounce handling)
