// Code generated by encx-gen. DO NOT EDIT.
// Source: media.go
// Generated: 2025-11-05T10:58:19+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// MediaFileEncx represents the encrypted version of MediaFile
type MediaFileEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	IsPublished bool `db:"ispublished" json:"ispublished"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	CaseIDEncrypted []byte `db:"caseid_encrypted" json:"caseid_encrypted"`
	
	URLEncrypted []byte `db:"url_encrypted" json:"url_encrypted"`
	
	TypeEncrypted []byte `db:"type_encrypted" json:"type_encrypted"`
	
	CaptionEncrypted []byte `db:"caption_encrypted" json:"caption_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessMediaFileEncx encrypts and hashes fields based on encx tags
func ProcessMediaFileEncx(ctx context.Context, crypto encx.CryptoService, source *MediaFile) (*MediaFileEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &MediaFileEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.IsPublished = source.IsPublished
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process CaseID (encrypt)
	if source.CaseID != uuid.Nil {
	CaseIDBytes, err := encx.SerializeValue(source.CaseID)
	if err != nil {
		errs.Set("CaseID serialization", err)
	} else {
		result.CaseIDEncrypted, err = crypto.EncryptData(ctx, CaseIDBytes, dek)
		if err != nil {
			errs.Set("CaseID encryption", err)
		}
	}
	}
	
	
	
	// Process URL (encrypt)
	URLBytes, err := encx.SerializeValue(source.URL)
	if err != nil {
		errs.Set("URL serialization", err)
	} else {
		result.URLEncrypted, err = crypto.EncryptData(ctx, URLBytes, dek)
		if err != nil {
			errs.Set("URL encryption", err)
		}
	}
	
	
	
	// Process Type (encrypt)
	TypeBytes, err := encx.SerializeValue(source.Type)
	if err != nil {
		errs.Set("Type serialization", err)
	} else {
		result.TypeEncrypted, err = crypto.EncryptData(ctx, TypeBytes, dek)
		if err != nil {
			errs.Set("Type encryption", err)
		}
	}
	
	
	
	// Process Caption (encrypt)
	CaptionBytes, err := encx.SerializeValue(source.Caption)
	if err != nil {
		errs.Set("Caption serialization", err)
	} else {
		result.CaptionEncrypted, err = crypto.EncryptData(ctx, CaptionBytes, dek)
		if err != nil {
			errs.Set("Caption encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptMediaFileEncx decrypts the encrypted struct back to original
func DecryptMediaFileEncx(ctx context.Context, crypto encx.CryptoService, source *MediaFileEncx) (*MediaFile, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &MediaFile{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.IsPublished = source.IsPublished
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt CaseID
	if len(source.CaseIDEncrypted) > 0 {
		CaseIDBytes, err := crypto.DecryptData(ctx, source.CaseIDEncrypted, dek)
		if err != nil {
			errs.Set("CaseID decryption", err)
		} else {
			err = encx.DeserializeValue(CaseIDBytes, &result.CaseID)
			if err != nil {
				errs.Set("CaseID deserialization", err)
			}
		}
	}
	
	
	// Decrypt URL
	if len(source.URLEncrypted) > 0 {
		URLBytes, err := crypto.DecryptData(ctx, source.URLEncrypted, dek)
		if err != nil {
			errs.Set("URL decryption", err)
		} else {
			err = encx.DeserializeValue(URLBytes, &result.URL)
			if err != nil {
				errs.Set("URL deserialization", err)
			}
		}
	}
	
	
	// Decrypt Type
	if len(source.TypeEncrypted) > 0 {
		TypeBytes, err := crypto.DecryptData(ctx, source.TypeEncrypted, dek)
		if err != nil {
			errs.Set("Type decryption", err)
		} else {
			err = encx.DeserializeValue(TypeBytes, &result.Type)
			if err != nil {
				errs.Set("Type deserialization", err)
			}
		}
	}
	
	
	// Decrypt Caption
	if len(source.CaptionEncrypted) > 0 {
		CaptionBytes, err := crypto.DecryptData(ctx, source.CaptionEncrypted, dek)
		if err != nil {
			errs.Set("Caption decryption", err)
		} else {
			err = encx.DeserializeValue(CaptionBytes, &result.Caption)
			if err != nil {
				errs.Set("Caption deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
