// Code generated by encx-gen. DO NOT EDIT.
// Source: signature.go
// Generated: 2025-12-11T17:30:34+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// SignatureEncx represents the encrypted version of Signature
type SignatureEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	Role string `db:"role" json:"role"`
	
	SignedAt time.Time `db:"signedat" json:"signedat"`
	
	Method string `db:"method" json:"method"`
	
	SignerID *uuid.UUID `db:"signerid" json:"signerid"`
	
	
	NameEncrypted []byte `db:"name_encrypted" json:"name_encrypted"`
	
	SignatureFileURLEncrypted []byte `db:"signaturefileurl_encrypted" json:"signaturefileurl_encrypted"`
	
	IPAddressEncrypted []byte `db:"ipaddress_encrypted" json:"ipaddress_encrypted"`
	
	UserAgentEncrypted []byte `db:"useragent_encrypted" json:"useragent_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessSignatureEncx encrypts and hashes fields based on encx tags
func ProcessSignatureEncx(ctx context.Context, crypto encx.CryptoService, source *Signature) (*SignatureEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &SignatureEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Role = source.Role
	
	result.SignedAt = source.SignedAt
	
	result.Method = source.Method
	
	result.SignerID = source.SignerID
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Name (encrypt)
	NameBytes, err := encx.SerializeValue(source.Name)
	if err != nil {
		errs.Set("Name serialization", err)
	} else {
		result.NameEncrypted, err = crypto.EncryptData(ctx, NameBytes, dek)
		if err != nil {
			errs.Set("Name encryption", err)
		}
	}
	
	
	
	// Process SignatureFileURL (encrypt)
	SignatureFileURLBytes, err := encx.SerializeValue(source.SignatureFileURL)
	if err != nil {
		errs.Set("SignatureFileURL serialization", err)
	} else {
		result.SignatureFileURLEncrypted, err = crypto.EncryptData(ctx, SignatureFileURLBytes, dek)
		if err != nil {
			errs.Set("SignatureFileURL encryption", err)
		}
	}
	
	
	
	// Process IPAddress (encrypt)
	if source.IPAddress != nil {
	IPAddressBytes, err := encx.SerializeValue(source.IPAddress)
	if err != nil {
		errs.Set("IPAddress serialization", err)
	} else {
		result.IPAddressEncrypted, err = crypto.EncryptData(ctx, IPAddressBytes, dek)
		if err != nil {
			errs.Set("IPAddress encryption", err)
		}
	}
	}
	
	
	
	// Process UserAgent (encrypt)
	if source.UserAgent != nil {
	UserAgentBytes, err := encx.SerializeValue(source.UserAgent)
	if err != nil {
		errs.Set("UserAgent serialization", err)
	} else {
		result.UserAgentEncrypted, err = crypto.EncryptData(ctx, UserAgentBytes, dek)
		if err != nil {
			errs.Set("UserAgent encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptSignatureEncx decrypts the encrypted struct back to original
func DecryptSignatureEncx(ctx context.Context, crypto encx.CryptoService, source *SignatureEncx) (*Signature, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Signature{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Role = source.Role
	
	result.SignedAt = source.SignedAt
	
	result.Method = source.Method
	
	result.SignerID = source.SignerID
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Name
	if len(source.NameEncrypted) > 0 {
		NameBytes, err := crypto.DecryptData(ctx, source.NameEncrypted, dek)
		if err != nil {
			errs.Set("Name decryption", err)
		} else {
			err = encx.DeserializeValue(NameBytes, &result.Name)
			if err != nil {
				errs.Set("Name deserialization", err)
			}
		}
	}
	
	
	// Decrypt SignatureFileURL
	if len(source.SignatureFileURLEncrypted) > 0 {
		SignatureFileURLBytes, err := crypto.DecryptData(ctx, source.SignatureFileURLEncrypted, dek)
		if err != nil {
			errs.Set("SignatureFileURL decryption", err)
		} else {
			err = encx.DeserializeValue(SignatureFileURLBytes, &result.SignatureFileURL)
			if err != nil {
				errs.Set("SignatureFileURL deserialization", err)
			}
		}
	}
	
	
	// Decrypt IPAddress
	if len(source.IPAddressEncrypted) > 0 {
		IPAddressBytes, err := crypto.DecryptData(ctx, source.IPAddressEncrypted, dek)
		if err != nil {
			errs.Set("IPAddress decryption", err)
		} else {
			err = encx.DeserializeValue(IPAddressBytes, &result.IPAddress)
			if err != nil {
				errs.Set("IPAddress deserialization", err)
			}
		}
	}
	
	
	// Decrypt UserAgent
	if len(source.UserAgentEncrypted) > 0 {
		UserAgentBytes, err := crypto.DecryptData(ctx, source.UserAgentEncrypted, dek)
		if err != nil {
			errs.Set("UserAgent decryption", err)
		} else {
			err = encx.DeserializeValue(UserAgentBytes, &result.UserAgent)
			if err != nil {
				errs.Set("UserAgent deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
