// Code generated by encx-gen. DO NOT EDIT.
// Source: token.go
// Generated: 2025-11-05T10:58:19+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// AccessTokenEncx represents the encrypted version of AccessToken
type AccessTokenEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	ClientID uuid.UUID `db:"clientid" json:"clientid"`
	
	ExpiresAt time.Time `db:"expiresat" json:"expiresat"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	CaseIDEncrypted []byte `db:"caseid_encrypted" json:"caseid_encrypted"`
	
	TokenEncrypted []byte `db:"token_encrypted" json:"token_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessAccessTokenEncx encrypts and hashes fields based on encx tags
func ProcessAccessTokenEncx(ctx context.Context, crypto encx.CryptoService, source *AccessToken) (*AccessTokenEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &AccessTokenEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ClientID = source.ClientID
	
	result.ExpiresAt = source.ExpiresAt
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process CaseID (encrypt)
	if source.CaseID != uuid.Nil {
	CaseIDBytes, err := encx.SerializeValue(source.CaseID)
	if err != nil {
		errs.Set("CaseID serialization", err)
	} else {
		result.CaseIDEncrypted, err = crypto.EncryptData(ctx, CaseIDBytes, dek)
		if err != nil {
			errs.Set("CaseID encryption", err)
		}
	}
	}
	
	
	
	// Process Token (encrypt)
	TokenBytes, err := encx.SerializeValue(source.Token)
	if err != nil {
		errs.Set("Token serialization", err)
	} else {
		result.TokenEncrypted, err = crypto.EncryptData(ctx, TokenBytes, dek)
		if err != nil {
			errs.Set("Token encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptAccessTokenEncx decrypts the encrypted struct back to original
func DecryptAccessTokenEncx(ctx context.Context, crypto encx.CryptoService, source *AccessTokenEncx) (*AccessToken, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &AccessToken{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.ClientID = source.ClientID
	
	result.ExpiresAt = source.ExpiresAt
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt CaseID
	if len(source.CaseIDEncrypted) > 0 {
		CaseIDBytes, err := crypto.DecryptData(ctx, source.CaseIDEncrypted, dek)
		if err != nil {
			errs.Set("CaseID decryption", err)
		} else {
			err = encx.DeserializeValue(CaseIDBytes, &result.CaseID)
			if err != nil {
				errs.Set("CaseID deserialization", err)
			}
		}
	}
	
	
	// Decrypt Token
	if len(source.TokenEncrypted) > 0 {
		TokenBytes, err := crypto.DecryptData(ctx, source.TokenEncrypted, dek)
		if err != nil {
			errs.Set("Token decryption", err)
		} else {
			err = encx.DeserializeValue(TokenBytes, &result.Token)
			if err != nil {
				errs.Set("Token deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
