<script lang="ts">
    import { Dialog } from "bits-ui";
    import { X, Download, RefreshCw, Check, AlertCircle, Loader2 } from "@lucide/svelte";
    import { onMount, onDestroy } from "svelte";
    import { EventsOn, EventsOff } from "$lib/wailsjs/runtime/runtime";

    // Types for the updater
    type UpdateInfo = {
        available: boolean;
        version: string;
        release_notes: string;
        download_url: string;
    };

    type ProgressEvent = {
        downloaded: number;
        total: number;
        percent: number;
    };

    type UpdateState = "idle" | "checking" | "available" | "uptodate" | "downloading" | "installing" | "ready" | "error";

    // Props
    type Props = {
        open?: boolean;
        onOpenChange?: (open: boolean) => void;
    };
    let { open = $bindable(false), onOpenChange }: Props = $props();

    // State
    let updateState: UpdateState = $state("idle");
    let updateInfo = $state<UpdateInfo | null>(null);
    let progress = $state<ProgressEvent>({ downloaded: 0, total: 0, percent: 0 });
    let errorMessage = $state<string>("");
    let currentVersion = $state<string>("");

    // Dynamically import the Updater bindings
    // These are generated by Wails at build time
    let Updater: {
        CheckForUpdate: () => Promise<UpdateInfo>;
        GetCurrentVersion: () => Promise<string>;
        DownloadAndInstall: () => Promise<void>;
        RestartApp: () => Promise<void>;
        CancelDownload: () => Promise<void>;
    } | null = $state(null);

    onMount(async () => {
        // Import the Updater bindings dynamically
        try {
            const module = await import("$lib/wailsjs/go/updater/Updater");
            Updater = module;
            if (Updater) {
                currentVersion = await Updater.GetCurrentVersion();
            }
        } catch (e) {
            console.warn("Updater bindings not available:", e);
        }

        // Listen for updater events
        EventsOn("updater:progress", (data: ProgressEvent) => {
            progress = data;
        });

        EventsOn("updater:status", (status: string) => {
            if (status === "downloading") {
                updateState = "downloading";
            } else if (status === "installing") {
                updateState = "installing";
            } else if (status === "ready") {
                updateState = "ready";
            }
        });

        EventsOn("updater:error", (message: string) => {
            errorMessage = message;
            updateState = "error";
        });
    });

    onDestroy(() => {
        EventsOff("updater:progress", "updater:status", "updater:error");
    });

    async function checkForUpdate() {
        if (!Updater) return;

        updateState = "checking";
        errorMessage = "";

        try {
            const info = await Updater.CheckForUpdate();
            updateInfo = info;
            updateState = info.available ? "available" : "uptodate";
        } catch (e) {
            errorMessage = e instanceof Error ? e.message : String(e);
            updateState = "error";
        }
    }

    async function downloadAndInstall() {
        if (!Updater) return;

        try {
            await Updater.DownloadAndInstall();
        } catch (e) {
            errorMessage = e instanceof Error ? e.message : String(e);
            updateState = "error";
        }
    }

    async function restartApp() {
        if (!Updater) return;

        try {
            await Updater.RestartApp();
        } catch (e) {
            errorMessage = e instanceof Error ? e.message : String(e);
            updateState = "error";
        }
    }

    function cancelDownload() {
        if (!Updater) return;
        Updater.CancelDownload();
        updateState = "available";
    }

    function formatBytes(bytes: number): string {
        if (bytes === 0) return "0 B";
        const k = 1024;
        const sizes = ["B", "KB", "MB", "GB"];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
    }

    function handleOpenChange(isOpen: boolean) {
        open = isOpen;
        onOpenChange?.(isOpen);
        if (isOpen && updateState === "idle") {
            checkForUpdate();
        }
    }

    // Auto-check when dialog opens
    $effect(() => {
        if (open && updateState === "idle" && Updater) {
            checkForUpdate();
        }
    });
</script>

<Dialog.Root bind:open onOpenChange={handleOpenChange}>
    <Dialog.Portal>
        <Dialog.Overlay
            class="data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 fixed inset-0 z-50 bg-black/80"
        />
        <Dialog.Content
            class="rounded-card-lg bg-background shadow-popover data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 outline-hidden fixed left-[50%] top-[50%] z-50 w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] border p-8 sm:max-w-[480px] md:w-full"
        >
            <Dialog.Title class="flex w-full items-center gap-2 text-lg font-semibold tracking-tight">
                {#if updateState === "checking"}
                    <Loader2 class="size-5 animate-spin" />
                    Checking for updates...
                {:else if updateState === "available"}
                    <Download class="size-5" />
                    Update Available
                {:else if updateState === "uptodate"}
                    <Check class="size-5 text-green-500" />
                    Up to Date
                {:else if updateState === "downloading"}
                    <Loader2 class="size-5 animate-spin" />
                    Downloading Update...
                {:else if updateState === "installing"}
                    <Loader2 class="size-5 animate-spin" />
                    Installing Update...
                {:else if updateState === "ready"}
                    <Check class="size-5 text-green-500" />
                    Update Ready
                {:else if updateState === "error"}
                    <AlertCircle class="size-5 text-red-500" />
                    Update Error
                {:else}
                    <RefreshCw class="size-5" />
                    Software Update
                {/if}
            </Dialog.Title>

            <div class="mt-4 space-y-4">
                {#if updateState === "checking"}
                    <p class="text-foreground-alt text-sm">
                        Checking for updates...
                    </p>
                {:else if updateState === "available" && updateInfo}
                    <div class="space-y-2">
                        <p class="text-foreground-alt text-sm">
                            A new version is available: <strong>v{updateInfo.version}</strong>
                        </p>
                        <p class="text-foreground-alt text-sm">
                            Current version: <strong>v{currentVersion}</strong>
                        </p>
                        {#if updateInfo.release_notes}
                            <div class="mt-3 rounded-md bg-muted p-3">
                                <p class="text-sm font-medium">Release Notes:</p>
                                <p class="text-foreground-alt mt-1 text-sm whitespace-pre-wrap">
                                    {updateInfo.release_notes}
                                </p>
                            </div>
                        {/if}
                    </div>
                {:else if updateState === "uptodate"}
                    <p class="text-foreground-alt text-sm">
                        You're running the latest version (<strong>v{currentVersion}</strong>).
                    </p>
                {:else if updateState === "downloading"}
                    <div class="space-y-2">
                        <div class="flex justify-between text-sm">
                            <span class="text-foreground-alt">
                                {formatBytes(progress.downloaded)} / {progress.total > 0 ? formatBytes(progress.total) : "..."}
                            </span>
                            <span class="font-medium">{progress.percent.toFixed(1)}%</span>
                        </div>
                        <div class="h-2 w-full overflow-hidden rounded-full bg-muted">
                            <div
                                class="h-full bg-primary transition-all duration-200"
                                style="width: {progress.percent}%"
                            ></div>
                        </div>
                    </div>
                {:else if updateState === "installing"}
                    <p class="text-foreground-alt text-sm">
                        Installing update, please wait...
                    </p>
                {:else if updateState === "ready"}
                    <p class="text-foreground-alt text-sm">
                        The update has been installed. Restart the application to apply the changes.
                    </p>
                {:else if updateState === "error"}
                    <div class="rounded-md bg-red-50 p-3 dark:bg-red-950">
                        <p class="text-sm text-red-600 dark:text-red-400">
                            {errorMessage || "An unknown error occurred."}
                        </p>
                    </div>
                {/if}
            </div>

            <div class="mt-6 flex justify-end gap-2">
                {#if updateState === "checking" || updateState === "installing"}
                    <!-- No actions during checking/installing -->
                {:else if updateState === "available"}
                    <Dialog.Close
                        class="h-input rounded-input bg-transparent text-dark hover:bg-[#fafafa] dark:text-white dark:hover:bg-white/10 focus-visible:ring-dark focus-visible:ring-offset-background focus-visible:outline-hidden inline-flex items-center justify-center px-4 py-2 text-[15px] font-semibold focus-visible:ring-2 focus-visible:ring-offset-2 active:scale-[0.98] border-2 border-[#dedede] dark:border-white/20 cursor-pointer"
                    >
                        Later
                    </Dialog.Close>
                    <button
                        onclick={downloadAndInstall}
                        class="h-input rounded-input bg-dark text-background shadow-mini hover:bg-dark/95 focus-visible:ring-dark focus-visible:ring-offset-background focus-visible:outline-hidden inline-flex items-center justify-center px-4 py-2 text-[15px] font-semibold focus-visible:ring-2 focus-visible:ring-offset-2 active:scale-[0.98] cursor-pointer"
                    >
                        Download & Install
                    </button>
                {:else if updateState === "downloading"}
                    <button
                        onclick={cancelDownload}
                        class="h-input rounded-input bg-transparent text-dark hover:bg-[#fafafa] dark:text-white dark:hover:bg-white/10 focus-visible:ring-dark focus-visible:ring-offset-background focus-visible:outline-hidden inline-flex items-center justify-center px-4 py-2 text-[15px] font-semibold focus-visible:ring-2 focus-visible:ring-offset-2 active:scale-[0.98] border-2 border-[#dedede] dark:border-white/20 cursor-pointer"
                    >
                        Cancel
                    </button>
                {:else if updateState === "ready"}
                    <Dialog.Close
                        class="h-input rounded-input bg-transparent text-dark hover:bg-[#fafafa] dark:text-white dark:hover:bg-white/10 focus-visible:ring-dark focus-visible:ring-offset-background focus-visible:outline-hidden inline-flex items-center justify-center px-4 py-2 text-[15px] font-semibold focus-visible:ring-2 focus-visible:ring-offset-2 active:scale-[0.98] border-2 border-[#dedede] dark:border-white/20 cursor-pointer"
                    >
                        Later
                    </Dialog.Close>
                    <button
                        onclick={restartApp}
                        class="h-input rounded-input bg-dark text-background shadow-mini hover:bg-dark/95 focus-visible:ring-dark focus-visible:ring-offset-background focus-visible:outline-hidden inline-flex items-center justify-center px-4 py-2 text-[15px] font-semibold focus-visible:ring-2 focus-visible:ring-offset-2 active:scale-[0.98] cursor-pointer"
                    >
                        Restart Now
                    </button>
                {:else if updateState === "uptodate" || updateState === "error"}
                    <Dialog.Close
                        class="h-input rounded-input bg-dark text-background shadow-mini hover:bg-dark/95 focus-visible:ring-dark focus-visible:ring-offset-background focus-visible:outline-hidden inline-flex items-center justify-center px-4 py-2 text-[15px] font-semibold focus-visible:ring-2 focus-visible:ring-offset-2 active:scale-[0.98] cursor-pointer"
                    >
                        Close
                    </Dialog.Close>
                {/if}
            </div>

            <Dialog.Close
                class="focus-visible:ring-foreground focus-visible:ring-offset-background focus-visible:outline-hidden absolute right-5 top-5 rounded-md focus-visible:ring-2 focus-visible:ring-offset-2 active:scale-[0.98] cursor-pointer"
            >
                <div>
                    <X class="text-foreground size-5" />
                    <span class="sr-only">Close</span>
                </div>
            </Dialog.Close>
        </Dialog.Content>
    </Dialog.Portal>
</Dialog.Root>
