// Code generated by encx-gen. DO NOT EDIT.
// Source: contract.go
// Generated: 2025-12-11T17:30:34+01:00

package document

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// ContractEncx represents the encrypted version of Contract
type ContractEncx struct {
	
	StartDate time.Time `db:"startdate" json:"startdate"`
	
	EndDate *time.Time `db:"enddate" json:"enddate"`
	
	LinkedMandateID *uuid.UUID `db:"linkedmandateid" json:"linkedmandateid"`
	
	Currency *string `db:"currency" json:"currency"`
	
	GoverningLaw *string `db:"governinglaw" json:"governinglaw"`
	
	
	ContractNumberEncrypted []byte `db:"contractnumber_encrypted" json:"contractnumber_encrypted"`
	
	ScopeOfServicesEncrypted []byte `db:"scopeofservices_encrypted" json:"scopeofservices_encrypted"`
	
	PaymentTermsEncrypted []byte `db:"paymentterms_encrypted" json:"paymentterms_encrypted"`
	
	ConfidentialityEncrypted []byte `db:"confidentiality_encrypted" json:"confidentiality_encrypted"`
	
	TerminationClauseEncrypted []byte `db:"terminationclause_encrypted" json:"terminationclause_encrypted"`
	
	SignaturesEncrypted []byte `db:"signatures_encrypted" json:"signatures_encrypted"`
	
	ContractValueEncrypted []byte `db:"contractvalue_encrypted" json:"contractvalue_encrypted"`
	
	RenewalTermsEncrypted []byte `db:"renewalterms_encrypted" json:"renewalterms_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessContractEncx encrypts and hashes fields based on encx tags
func ProcessContractEncx(ctx context.Context, crypto encx.CryptoService, source *Contract) (*ContractEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &ContractEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.StartDate = source.StartDate
	
	result.EndDate = source.EndDate
	
	result.LinkedMandateID = source.LinkedMandateID
	
	result.Currency = source.Currency
	
	result.GoverningLaw = source.GoverningLaw
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process ContractNumber (encrypt)
	ContractNumberBytes, err := encx.SerializeValue(source.ContractNumber)
	if err != nil {
		errs.Set("ContractNumber serialization", err)
	} else {
		result.ContractNumberEncrypted, err = crypto.EncryptData(ctx, ContractNumberBytes, dek)
		if err != nil {
			errs.Set("ContractNumber encryption", err)
		}
	}
	
	
	
	// Process ScopeOfServices (encrypt)
	ScopeOfServicesBytes, err := encx.SerializeValue(source.ScopeOfServices)
	if err != nil {
		errs.Set("ScopeOfServices serialization", err)
	} else {
		result.ScopeOfServicesEncrypted, err = crypto.EncryptData(ctx, ScopeOfServicesBytes, dek)
		if err != nil {
			errs.Set("ScopeOfServices encryption", err)
		}
	}
	
	
	
	// Process PaymentTerms (encrypt)
	PaymentTermsBytes, err := encx.SerializeValue(source.PaymentTerms)
	if err != nil {
		errs.Set("PaymentTerms serialization", err)
	} else {
		result.PaymentTermsEncrypted, err = crypto.EncryptData(ctx, PaymentTermsBytes, dek)
		if err != nil {
			errs.Set("PaymentTerms encryption", err)
		}
	}
	
	
	
	// Process Confidentiality (encrypt)
	ConfidentialityBytes, err := encx.SerializeValue(source.Confidentiality)
	if err != nil {
		errs.Set("Confidentiality serialization", err)
	} else {
		result.ConfidentialityEncrypted, err = crypto.EncryptData(ctx, ConfidentialityBytes, dek)
		if err != nil {
			errs.Set("Confidentiality encryption", err)
		}
	}
	
	
	
	// Process TerminationClause (encrypt)
	TerminationClauseBytes, err := encx.SerializeValue(source.TerminationClause)
	if err != nil {
		errs.Set("TerminationClause serialization", err)
	} else {
		result.TerminationClauseEncrypted, err = crypto.EncryptData(ctx, TerminationClauseBytes, dek)
		if err != nil {
			errs.Set("TerminationClause encryption", err)
		}
	}
	
	
	
	// Process Signatures (encrypt)
	SignaturesBytes, err := encx.SerializeValue(source.Signatures)
	if err != nil {
		errs.Set("Signatures serialization", err)
	} else {
		result.SignaturesEncrypted, err = crypto.EncryptData(ctx, SignaturesBytes, dek)
		if err != nil {
			errs.Set("Signatures encryption", err)
		}
	}
	
	
	
	// Process ContractValue (encrypt)
	if source.ContractValue != nil {
	ContractValueBytes, err := encx.SerializeValue(source.ContractValue)
	if err != nil {
		errs.Set("ContractValue serialization", err)
	} else {
		result.ContractValueEncrypted, err = crypto.EncryptData(ctx, ContractValueBytes, dek)
		if err != nil {
			errs.Set("ContractValue encryption", err)
		}
	}
	}
	
	
	
	// Process RenewalTerms (encrypt)
	if source.RenewalTerms != nil {
	RenewalTermsBytes, err := encx.SerializeValue(source.RenewalTerms)
	if err != nil {
		errs.Set("RenewalTerms serialization", err)
	} else {
		result.RenewalTermsEncrypted, err = crypto.EncryptData(ctx, RenewalTermsBytes, dek)
		if err != nil {
			errs.Set("RenewalTerms encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptContractEncx decrypts the encrypted struct back to original
func DecryptContractEncx(ctx context.Context, crypto encx.CryptoService, source *ContractEncx) (*Contract, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Contract{}

	// Copy plain fields (non-encx fields)
	
	result.StartDate = source.StartDate
	
	result.EndDate = source.EndDate
	
	result.LinkedMandateID = source.LinkedMandateID
	
	result.Currency = source.Currency
	
	result.GoverningLaw = source.GoverningLaw
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt ContractNumber
	if len(source.ContractNumberEncrypted) > 0 {
		ContractNumberBytes, err := crypto.DecryptData(ctx, source.ContractNumberEncrypted, dek)
		if err != nil {
			errs.Set("ContractNumber decryption", err)
		} else {
			err = encx.DeserializeValue(ContractNumberBytes, &result.ContractNumber)
			if err != nil {
				errs.Set("ContractNumber deserialization", err)
			}
		}
	}
	
	
	// Decrypt ScopeOfServices
	if len(source.ScopeOfServicesEncrypted) > 0 {
		ScopeOfServicesBytes, err := crypto.DecryptData(ctx, source.ScopeOfServicesEncrypted, dek)
		if err != nil {
			errs.Set("ScopeOfServices decryption", err)
		} else {
			err = encx.DeserializeValue(ScopeOfServicesBytes, &result.ScopeOfServices)
			if err != nil {
				errs.Set("ScopeOfServices deserialization", err)
			}
		}
	}
	
	
	// Decrypt PaymentTerms
	if len(source.PaymentTermsEncrypted) > 0 {
		PaymentTermsBytes, err := crypto.DecryptData(ctx, source.PaymentTermsEncrypted, dek)
		if err != nil {
			errs.Set("PaymentTerms decryption", err)
		} else {
			err = encx.DeserializeValue(PaymentTermsBytes, &result.PaymentTerms)
			if err != nil {
				errs.Set("PaymentTerms deserialization", err)
			}
		}
	}
	
	
	// Decrypt Confidentiality
	if len(source.ConfidentialityEncrypted) > 0 {
		ConfidentialityBytes, err := crypto.DecryptData(ctx, source.ConfidentialityEncrypted, dek)
		if err != nil {
			errs.Set("Confidentiality decryption", err)
		} else {
			err = encx.DeserializeValue(ConfidentialityBytes, &result.Confidentiality)
			if err != nil {
				errs.Set("Confidentiality deserialization", err)
			}
		}
	}
	
	
	// Decrypt TerminationClause
	if len(source.TerminationClauseEncrypted) > 0 {
		TerminationClauseBytes, err := crypto.DecryptData(ctx, source.TerminationClauseEncrypted, dek)
		if err != nil {
			errs.Set("TerminationClause decryption", err)
		} else {
			err = encx.DeserializeValue(TerminationClauseBytes, &result.TerminationClause)
			if err != nil {
				errs.Set("TerminationClause deserialization", err)
			}
		}
	}
	
	
	// Decrypt Signatures
	if len(source.SignaturesEncrypted) > 0 {
		SignaturesBytes, err := crypto.DecryptData(ctx, source.SignaturesEncrypted, dek)
		if err != nil {
			errs.Set("Signatures decryption", err)
		} else {
			err = encx.DeserializeValue(SignaturesBytes, &result.Signatures)
			if err != nil {
				errs.Set("Signatures deserialization", err)
			}
		}
	}
	
	
	// Decrypt ContractValue
	if len(source.ContractValueEncrypted) > 0 {
		ContractValueBytes, err := crypto.DecryptData(ctx, source.ContractValueEncrypted, dek)
		if err != nil {
			errs.Set("ContractValue decryption", err)
		} else {
			err = encx.DeserializeValue(ContractValueBytes, &result.ContractValue)
			if err != nil {
				errs.Set("ContractValue deserialization", err)
			}
		}
	}
	
	
	// Decrypt RenewalTerms
	if len(source.RenewalTermsEncrypted) > 0 {
		RenewalTermsBytes, err := crypto.DecryptData(ctx, source.RenewalTermsEncrypted, dek)
		if err != nil {
			errs.Set("RenewalTerms decryption", err)
		} else {
			err = encx.DeserializeValue(RenewalTermsBytes, &result.RenewalTerms)
			if err != nil {
				errs.Set("RenewalTerms deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
