// Code generated by encx-gen. DO NOT EDIT.
// Source: document_base.go
// Generated: 2025-11-05T10:58:19+01:00

package domain

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// DocumentBaseEncx represents the encrypted version of DocumentBase
type DocumentBaseEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	Status DocumentStatus `db:"status" json:"status"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	
	CaseIDEncrypted []byte `db:"caseid_encrypted" json:"caseid_encrypted"`
	
	ClientIDEncrypted []byte `db:"clientid_encrypted" json:"clientid_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessDocumentBaseEncx encrypts and hashes fields based on encx tags
func ProcessDocumentBaseEncx(ctx context.Context, crypto encx.CryptoService, source *DocumentBase) (*DocumentBaseEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &DocumentBaseEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process CaseID (encrypt)
	if source.CaseID != uuid.Nil {
	CaseIDBytes, err := encx.SerializeValue(source.CaseID)
	if err != nil {
		errs.Set("CaseID serialization", err)
	} else {
		result.CaseIDEncrypted, err = crypto.EncryptData(ctx, CaseIDBytes, dek)
		if err != nil {
			errs.Set("CaseID encryption", err)
		}
	}
	}
	
	
	
	// Process ClientID (encrypt)
	if source.ClientID != uuid.Nil {
	ClientIDBytes, err := encx.SerializeValue(source.ClientID)
	if err != nil {
		errs.Set("ClientID serialization", err)
	} else {
		result.ClientIDEncrypted, err = crypto.EncryptData(ctx, ClientIDBytes, dek)
		if err != nil {
			errs.Set("ClientID encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptDocumentBaseEncx decrypts the encrypted struct back to original
func DecryptDocumentBaseEncx(ctx context.Context, crypto encx.CryptoService, source *DocumentBaseEncx) (*DocumentBase, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &DocumentBase{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt CaseID
	if len(source.CaseIDEncrypted) > 0 {
		CaseIDBytes, err := crypto.DecryptData(ctx, source.CaseIDEncrypted, dek)
		if err != nil {
			errs.Set("CaseID decryption", err)
		} else {
			err = encx.DeserializeValue(CaseIDBytes, &result.CaseID)
			if err != nil {
				errs.Set("CaseID deserialization", err)
			}
		}
	}
	
	
	// Decrypt ClientID
	if len(source.ClientIDEncrypted) > 0 {
		ClientIDBytes, err := crypto.DecryptData(ctx, source.ClientIDEncrypted, dek)
		if err != nil {
			errs.Set("ClientID decryption", err)
		} else {
			err = encx.DeserializeValue(ClientIDBytes, &result.ClientID)
			if err != nil {
				errs.Set("ClientID deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
