// Code generated by encx-gen. DO NOT EDIT.
// Source: estimate.go
// Generated: 2025-12-11T17:30:34+01:00

package document

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// EstimateEncx represents the encrypted version of Estimate
type EstimateEncx struct {
	
	IssueDate time.Time `db:"issuedate" json:"issuedate"`
	
	ValidUntil *time.Time `db:"validuntil" json:"validuntil"`
	
	Accepted bool `db:"accepted" json:"accepted"`
	
	AcceptedAt *time.Time `db:"acceptedat" json:"acceptedat"`
	
	AcceptedBy *uuid.UUID `db:"acceptedby" json:"acceptedby"`
	
	
	EstimateNumberEncrypted []byte `db:"estimatenumber_encrypted" json:"estimatenumber_encrypted"`
	
	LineItemsEncrypted []byte `db:"lineitems_encrypted" json:"lineitems_encrypted"`
	
	EstimatedTotalEncrypted []byte `db:"estimatedtotal_encrypted" json:"estimatedtotal_encrypted"`
	
	NotesEncrypted []byte `db:"notes_encrypted" json:"notes_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessEstimateEncx encrypts and hashes fields based on encx tags
func ProcessEstimateEncx(ctx context.Context, crypto encx.CryptoService, source *Estimate) (*EstimateEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &EstimateEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.IssueDate = source.IssueDate
	
	result.ValidUntil = source.ValidUntil
	
	result.Accepted = source.Accepted
	
	result.AcceptedAt = source.AcceptedAt
	
	result.AcceptedBy = source.AcceptedBy
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process EstimateNumber (encrypt)
	EstimateNumberBytes, err := encx.SerializeValue(source.EstimateNumber)
	if err != nil {
		errs.Set("EstimateNumber serialization", err)
	} else {
		result.EstimateNumberEncrypted, err = crypto.EncryptData(ctx, EstimateNumberBytes, dek)
		if err != nil {
			errs.Set("EstimateNumber encryption", err)
		}
	}
	
	
	
	// Process LineItems (encrypt)
	LineItemsBytes, err := encx.SerializeValue(source.LineItems)
	if err != nil {
		errs.Set("LineItems serialization", err)
	} else {
		result.LineItemsEncrypted, err = crypto.EncryptData(ctx, LineItemsBytes, dek)
		if err != nil {
			errs.Set("LineItems encryption", err)
		}
	}
	
	
	
	// Process EstimatedTotal (encrypt)
	EstimatedTotalBytes, err := encx.SerializeValue(source.EstimatedTotal)
	if err != nil {
		errs.Set("EstimatedTotal serialization", err)
	} else {
		result.EstimatedTotalEncrypted, err = crypto.EncryptData(ctx, EstimatedTotalBytes, dek)
		if err != nil {
			errs.Set("EstimatedTotal encryption", err)
		}
	}
	
	
	
	// Process Notes (encrypt)
	if source.Notes != nil {
	NotesBytes, err := encx.SerializeValue(source.Notes)
	if err != nil {
		errs.Set("Notes serialization", err)
	} else {
		result.NotesEncrypted, err = crypto.EncryptData(ctx, NotesBytes, dek)
		if err != nil {
			errs.Set("Notes encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptEstimateEncx decrypts the encrypted struct back to original
func DecryptEstimateEncx(ctx context.Context, crypto encx.CryptoService, source *EstimateEncx) (*Estimate, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Estimate{}

	// Copy plain fields (non-encx fields)
	
	result.IssueDate = source.IssueDate
	
	result.ValidUntil = source.ValidUntil
	
	result.Accepted = source.Accepted
	
	result.AcceptedAt = source.AcceptedAt
	
	result.AcceptedBy = source.AcceptedBy
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt EstimateNumber
	if len(source.EstimateNumberEncrypted) > 0 {
		EstimateNumberBytes, err := crypto.DecryptData(ctx, source.EstimateNumberEncrypted, dek)
		if err != nil {
			errs.Set("EstimateNumber decryption", err)
		} else {
			err = encx.DeserializeValue(EstimateNumberBytes, &result.EstimateNumber)
			if err != nil {
				errs.Set("EstimateNumber deserialization", err)
			}
		}
	}
	
	
	// Decrypt LineItems
	if len(source.LineItemsEncrypted) > 0 {
		LineItemsBytes, err := crypto.DecryptData(ctx, source.LineItemsEncrypted, dek)
		if err != nil {
			errs.Set("LineItems decryption", err)
		} else {
			err = encx.DeserializeValue(LineItemsBytes, &result.LineItems)
			if err != nil {
				errs.Set("LineItems deserialization", err)
			}
		}
	}
	
	
	// Decrypt EstimatedTotal
	if len(source.EstimatedTotalEncrypted) > 0 {
		EstimatedTotalBytes, err := crypto.DecryptData(ctx, source.EstimatedTotalEncrypted, dek)
		if err != nil {
			errs.Set("EstimatedTotal decryption", err)
		} else {
			err = encx.DeserializeValue(EstimatedTotalBytes, &result.EstimatedTotal)
			if err != nil {
				errs.Set("EstimatedTotal deserialization", err)
			}
		}
	}
	
	
	// Decrypt Notes
	if len(source.NotesEncrypted) > 0 {
		NotesBytes, err := crypto.DecryptData(ctx, source.NotesEncrypted, dek)
		if err != nil {
			errs.Set("Notes decryption", err)
		} else {
			err = encx.DeserializeValue(NotesBytes, &result.Notes)
			if err != nil {
				errs.Set("Notes deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
