// Code generated by encx-gen. DO NOT EDIT.
// Source: invoice.go
// Generated: 2026-06-08T09:31:07+02:00

package document

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"encoding/json"
	
	"github.com/google/uuid"
	
)

// InvoiceEncx represents the encrypted version of Invoice
type InvoiceEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	Status DocumentStatus `db:"status" json:"status"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	IssueDate time.Time `db:"issuedate" json:"issuedate"`
	
	DueDate time.Time `db:"duedate" json:"duedate"`
	
	TaxRate float64 `db:"taxrate" json:"taxrate"`
	
	PaymentStatus PaymentStatus `db:"paymentstatus" json:"paymentstatus"`
	
	PaidAt *time.Time `db:"paidat" json:"paidat"`
	
	LinkedContractID *uuid.UUID `db:"linkedcontractid" json:"linkedcontractid"`
	
	Currency *string `db:"currency" json:"currency"`
	
	LateFeeRate *float64 `db:"latefeerate" json:"latefeerate"`
	
	
	CaseIDEncrypted []byte `db:"caseid_encrypted" json:"caseid_encrypted"`
	
	ClientIDEncrypted []byte `db:"clientid_encrypted" json:"clientid_encrypted"`
	
	InvoiceNumberEncrypted []byte `db:"invoicenumber_encrypted" json:"invoicenumber_encrypted"`
	
	LineItemsEncrypted []byte `db:"lineitems_encrypted" json:"lineitems_encrypted"`
	
	TotalAmountEncrypted []byte `db:"totalamount_encrypted" json:"totalamount_encrypted"`
	
	TaxAmountEncrypted []byte `db:"taxamount_encrypted" json:"taxamount_encrypted"`
	
	NotesEncrypted []byte `db:"notes_encrypted" json:"notes_encrypted"`
	
	PaidAmountEncrypted []byte `db:"paidamount_encrypted" json:"paidamount_encrypted"`
	
	PaymentMethodEncrypted []byte `db:"paymentmethod_encrypted" json:"paymentmethod_encrypted"`
	
	PaymentTermsEncrypted []byte `db:"paymentterms_encrypted" json:"paymentterms_encrypted"`
	
	LateFeeEncrypted []byte `db:"latefee_encrypted" json:"latefee_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessInvoiceEncx encrypts and hashes fields based on encx tags
func ProcessInvoiceEncx(ctx context.Context, crypto encx.CryptoService, source *Invoice) (*InvoiceEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &InvoiceEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.IssueDate = source.IssueDate
	
	result.DueDate = source.DueDate
	
	result.TaxRate = source.TaxRate
	
	result.PaymentStatus = source.PaymentStatus
	
	result.PaidAt = source.PaidAt
	
	result.LinkedContractID = source.LinkedContractID
	
	result.Currency = source.Currency
	
	result.LateFeeRate = source.LateFeeRate
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process CaseID (encrypt)
	if source.CaseID != uuid.Nil {
	CaseIDBytes, err := encx.SerializeValue(source.CaseID)
	if err != nil {
		errs.Set("CaseID serialization", err)
	} else {
		result.CaseIDEncrypted, err = crypto.EncryptData(ctx, CaseIDBytes, dek)
		if err != nil {
			errs.Set("CaseID encryption", err)
		}
	}
	}
	
	
	
	// Process ClientID (encrypt)
	if source.ClientID != uuid.Nil {
	ClientIDBytes, err := encx.SerializeValue(source.ClientID)
	if err != nil {
		errs.Set("ClientID serialization", err)
	} else {
		result.ClientIDEncrypted, err = crypto.EncryptData(ctx, ClientIDBytes, dek)
		if err != nil {
			errs.Set("ClientID encryption", err)
		}
	}
	}
	
	
	
	// Process InvoiceNumber (encrypt)
	InvoiceNumberBytes, err := encx.SerializeValue(source.InvoiceNumber)
	if err != nil {
		errs.Set("InvoiceNumber serialization", err)
	} else {
		result.InvoiceNumberEncrypted, err = crypto.EncryptData(ctx, InvoiceNumberBytes, dek)
		if err != nil {
			errs.Set("InvoiceNumber encryption", err)
		}
	}
	
	
	
	// Process LineItems (encrypt, json)
	LineItemsBytes, err := json.Marshal(source.LineItems)
	if err != nil {
		errs.Set("LineItems serialization", err)
	} else {
		result.LineItemsEncrypted, err = crypto.EncryptData(ctx, LineItemsBytes, dek)
		if err != nil {
			errs.Set("LineItems encryption", err)
		}
	}
	
	
	
	// Process TotalAmount (encrypt)
	TotalAmountBytes, err := encx.SerializeValue(source.TotalAmount)
	if err != nil {
		errs.Set("TotalAmount serialization", err)
	} else {
		result.TotalAmountEncrypted, err = crypto.EncryptData(ctx, TotalAmountBytes, dek)
		if err != nil {
			errs.Set("TotalAmount encryption", err)
		}
	}
	
	
	
	// Process TaxAmount (encrypt)
	TaxAmountBytes, err := encx.SerializeValue(source.TaxAmount)
	if err != nil {
		errs.Set("TaxAmount serialization", err)
	} else {
		result.TaxAmountEncrypted, err = crypto.EncryptData(ctx, TaxAmountBytes, dek)
		if err != nil {
			errs.Set("TaxAmount encryption", err)
		}
	}
	
	
	
	// Process Notes (encrypt)
	if source.Notes != nil {
	NotesBytes, err := encx.SerializeValue(source.Notes)
	if err != nil {
		errs.Set("Notes serialization", err)
	} else {
		result.NotesEncrypted, err = crypto.EncryptData(ctx, NotesBytes, dek)
		if err != nil {
			errs.Set("Notes encryption", err)
		}
	}
	}
	
	
	
	// Process PaidAmount (encrypt)
	if source.PaidAmount != nil {
	PaidAmountBytes, err := encx.SerializeValue(source.PaidAmount)
	if err != nil {
		errs.Set("PaidAmount serialization", err)
	} else {
		result.PaidAmountEncrypted, err = crypto.EncryptData(ctx, PaidAmountBytes, dek)
		if err != nil {
			errs.Set("PaidAmount encryption", err)
		}
	}
	}
	
	
	
	// Process PaymentMethod (encrypt)
	if source.PaymentMethod != nil {
	PaymentMethodBytes, err := encx.SerializeValue(source.PaymentMethod)
	if err != nil {
		errs.Set("PaymentMethod serialization", err)
	} else {
		result.PaymentMethodEncrypted, err = crypto.EncryptData(ctx, PaymentMethodBytes, dek)
		if err != nil {
			errs.Set("PaymentMethod encryption", err)
		}
	}
	}
	
	
	
	// Process PaymentTerms (encrypt)
	if source.PaymentTerms != nil {
	PaymentTermsBytes, err := encx.SerializeValue(source.PaymentTerms)
	if err != nil {
		errs.Set("PaymentTerms serialization", err)
	} else {
		result.PaymentTermsEncrypted, err = crypto.EncryptData(ctx, PaymentTermsBytes, dek)
		if err != nil {
			errs.Set("PaymentTerms encryption", err)
		}
	}
	}
	
	
	
	// Process LateFee (encrypt)
	if source.LateFee != nil {
	LateFeeBytes, err := encx.SerializeValue(source.LateFee)
	if err != nil {
		errs.Set("LateFee serialization", err)
	} else {
		result.LateFeeEncrypted, err = crypto.EncryptData(ctx, LateFeeBytes, dek)
		if err != nil {
			errs.Set("LateFee encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptInvoiceEncx decrypts the encrypted struct back to original
func DecryptInvoiceEncx(ctx context.Context, crypto encx.CryptoService, source *InvoiceEncx) (*Invoice, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Invoice{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.IssueDate = source.IssueDate
	
	result.DueDate = source.DueDate
	
	result.TaxRate = source.TaxRate
	
	result.PaymentStatus = source.PaymentStatus
	
	result.PaidAt = source.PaidAt
	
	result.LinkedContractID = source.LinkedContractID
	
	result.Currency = source.Currency
	
	result.LateFeeRate = source.LateFeeRate
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt CaseID
	if len(source.CaseIDEncrypted) > 0 {
		CaseIDBytes, err := crypto.DecryptData(ctx, source.CaseIDEncrypted, dek)
		if err != nil {
			errs.Set("CaseID decryption", err)
		} else {
			err = encx.DeserializeValue(CaseIDBytes, &result.CaseID)
			if err != nil {
				errs.Set("CaseID deserialization", err)
			}
		}
	}
	
	
	// Decrypt ClientID
	if len(source.ClientIDEncrypted) > 0 {
		ClientIDBytes, err := crypto.DecryptData(ctx, source.ClientIDEncrypted, dek)
		if err != nil {
			errs.Set("ClientID decryption", err)
		} else {
			err = encx.DeserializeValue(ClientIDBytes, &result.ClientID)
			if err != nil {
				errs.Set("ClientID deserialization", err)
			}
		}
	}
	
	
	// Decrypt InvoiceNumber
	if len(source.InvoiceNumberEncrypted) > 0 {
		InvoiceNumberBytes, err := crypto.DecryptData(ctx, source.InvoiceNumberEncrypted, dek)
		if err != nil {
			errs.Set("InvoiceNumber decryption", err)
		} else {
			err = encx.DeserializeValue(InvoiceNumberBytes, &result.InvoiceNumber)
			if err != nil {
				errs.Set("InvoiceNumber deserialization", err)
			}
		}
	}
	
	
	// Decrypt LineItems
	if len(source.LineItemsEncrypted) > 0 {
		LineItemsBytes, err := crypto.DecryptData(ctx, source.LineItemsEncrypted, dek)
		if err != nil {
			errs.Set("LineItems decryption", err)
		} else {
			err = json.Unmarshal(LineItemsBytes, &result.LineItems)
			if err != nil {
				errs.Set("LineItems deserialization", err)
			}
		}
	}
	
	
	// Decrypt TotalAmount
	if len(source.TotalAmountEncrypted) > 0 {
		TotalAmountBytes, err := crypto.DecryptData(ctx, source.TotalAmountEncrypted, dek)
		if err != nil {
			errs.Set("TotalAmount decryption", err)
		} else {
			err = encx.DeserializeValue(TotalAmountBytes, &result.TotalAmount)
			if err != nil {
				errs.Set("TotalAmount deserialization", err)
			}
		}
	}
	
	
	// Decrypt TaxAmount
	if len(source.TaxAmountEncrypted) > 0 {
		TaxAmountBytes, err := crypto.DecryptData(ctx, source.TaxAmountEncrypted, dek)
		if err != nil {
			errs.Set("TaxAmount decryption", err)
		} else {
			err = encx.DeserializeValue(TaxAmountBytes, &result.TaxAmount)
			if err != nil {
				errs.Set("TaxAmount deserialization", err)
			}
		}
	}
	
	
	// Decrypt Notes
	if len(source.NotesEncrypted) > 0 {
		NotesBytes, err := crypto.DecryptData(ctx, source.NotesEncrypted, dek)
		if err != nil {
			errs.Set("Notes decryption", err)
		} else {
			err = encx.DeserializeValue(NotesBytes, &result.Notes)
			if err != nil {
				errs.Set("Notes deserialization", err)
			}
		}
	}
	
	
	// Decrypt PaidAmount
	if len(source.PaidAmountEncrypted) > 0 {
		PaidAmountBytes, err := crypto.DecryptData(ctx, source.PaidAmountEncrypted, dek)
		if err != nil {
			errs.Set("PaidAmount decryption", err)
		} else {
			err = encx.DeserializeValue(PaidAmountBytes, &result.PaidAmount)
			if err != nil {
				errs.Set("PaidAmount deserialization", err)
			}
		}
	}
	
	
	// Decrypt PaymentMethod
	if len(source.PaymentMethodEncrypted) > 0 {
		PaymentMethodBytes, err := crypto.DecryptData(ctx, source.PaymentMethodEncrypted, dek)
		if err != nil {
			errs.Set("PaymentMethod decryption", err)
		} else {
			err = encx.DeserializeValue(PaymentMethodBytes, &result.PaymentMethod)
			if err != nil {
				errs.Set("PaymentMethod deserialization", err)
			}
		}
	}
	
	
	// Decrypt PaymentTerms
	if len(source.PaymentTermsEncrypted) > 0 {
		PaymentTermsBytes, err := crypto.DecryptData(ctx, source.PaymentTermsEncrypted, dek)
		if err != nil {
			errs.Set("PaymentTerms decryption", err)
		} else {
			err = encx.DeserializeValue(PaymentTermsBytes, &result.PaymentTerms)
			if err != nil {
				errs.Set("PaymentTerms deserialization", err)
			}
		}
	}
	
	
	// Decrypt LateFee
	if len(source.LateFeeEncrypted) > 0 {
		LateFeeBytes, err := crypto.DecryptData(ctx, source.LateFeeEncrypted, dek)
		if err != nil {
			errs.Set("LateFee decryption", err)
		} else {
			err = encx.DeserializeValue(LateFeeBytes, &result.LateFee)
			if err != nil {
				errs.Set("LateFee deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
