// Code generated by encx-gen. DO NOT EDIT.
// Source: mandate.go
// Generated: 2026-06-08T09:31:07+02:00

package document

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"encoding/json"
	
	"github.com/google/uuid"
	
)

// MandateEncx represents the encrypted version of Mandate
type MandateEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	Status DocumentStatus `db:"status" json:"status"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	UpdatedAt time.Time `db:"updatedat" json:"updatedat"`
	
	IssueDate time.Time `db:"issuedate" json:"issuedate"`
	
	ValidFrom time.Time `db:"validfrom" json:"validfrom"`
	
	ValidUntil *time.Time `db:"validuntil" json:"validuntil"`
	
	LinkedEstimateID *uuid.UUID `db:"linkedestimateid" json:"linkedestimateid"`
	
	Jurisdiction *string `db:"jurisdiction" json:"jurisdiction"`
	
	
	CaseIDEncrypted []byte `db:"caseid_encrypted" json:"caseid_encrypted"`
	
	ClientIDEncrypted []byte `db:"clientid_encrypted" json:"clientid_encrypted"`
	
	MandateNumberEncrypted []byte `db:"mandatenumber_encrypted" json:"mandatenumber_encrypted"`
	
	ScopeOfWorkEncrypted []byte `db:"scopeofwork_encrypted" json:"scopeofwork_encrypted"`
	
	TermsConditionsEncrypted []byte `db:"termsconditions_encrypted" json:"termsconditions_encrypted"`
	
	ClientSignatureEncrypted []byte `db:"clientsignature_encrypted" json:"clientsignature_encrypted"`
	
	InvestigatorSignatureEncrypted []byte `db:"investigatorsignature_encrypted" json:"investigatorsignature_encrypted"`
	
	SpecialInstructionsEncrypted []byte `db:"specialinstructions_encrypted" json:"specialinstructions_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessMandateEncx encrypts and hashes fields based on encx tags
func ProcessMandateEncx(ctx context.Context, crypto encx.CryptoService, source *Mandate) (*MandateEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &MandateEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.IssueDate = source.IssueDate
	
	result.ValidFrom = source.ValidFrom
	
	result.ValidUntil = source.ValidUntil
	
	result.LinkedEstimateID = source.LinkedEstimateID
	
	result.Jurisdiction = source.Jurisdiction
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process CaseID (encrypt)
	if source.CaseID != uuid.Nil {
	CaseIDBytes, err := encx.SerializeValue(source.CaseID)
	if err != nil {
		errs.Set("CaseID serialization", err)
	} else {
		result.CaseIDEncrypted, err = crypto.EncryptData(ctx, CaseIDBytes, dek)
		if err != nil {
			errs.Set("CaseID encryption", err)
		}
	}
	}
	
	
	
	// Process ClientID (encrypt)
	if source.ClientID != uuid.Nil {
	ClientIDBytes, err := encx.SerializeValue(source.ClientID)
	if err != nil {
		errs.Set("ClientID serialization", err)
	} else {
		result.ClientIDEncrypted, err = crypto.EncryptData(ctx, ClientIDBytes, dek)
		if err != nil {
			errs.Set("ClientID encryption", err)
		}
	}
	}
	
	
	
	// Process MandateNumber (encrypt)
	MandateNumberBytes, err := encx.SerializeValue(source.MandateNumber)
	if err != nil {
		errs.Set("MandateNumber serialization", err)
	} else {
		result.MandateNumberEncrypted, err = crypto.EncryptData(ctx, MandateNumberBytes, dek)
		if err != nil {
			errs.Set("MandateNumber encryption", err)
		}
	}
	
	
	
	// Process ScopeOfWork (encrypt)
	ScopeOfWorkBytes, err := encx.SerializeValue(source.ScopeOfWork)
	if err != nil {
		errs.Set("ScopeOfWork serialization", err)
	} else {
		result.ScopeOfWorkEncrypted, err = crypto.EncryptData(ctx, ScopeOfWorkBytes, dek)
		if err != nil {
			errs.Set("ScopeOfWork encryption", err)
		}
	}
	
	
	
	// Process TermsConditions (encrypt)
	TermsConditionsBytes, err := encx.SerializeValue(source.TermsConditions)
	if err != nil {
		errs.Set("TermsConditions serialization", err)
	} else {
		result.TermsConditionsEncrypted, err = crypto.EncryptData(ctx, TermsConditionsBytes, dek)
		if err != nil {
			errs.Set("TermsConditions encryption", err)
		}
	}
	
	
	
	// Process ClientSignature (encrypt, json)
	if source.ClientSignature != nil {
	ClientSignatureBytes, err := json.Marshal(source.ClientSignature)
	if err != nil {
		errs.Set("ClientSignature serialization", err)
	} else {
		result.ClientSignatureEncrypted, err = crypto.EncryptData(ctx, ClientSignatureBytes, dek)
		if err != nil {
			errs.Set("ClientSignature encryption", err)
		}
	}
	}
	
	
	
	// Process InvestigatorSignature (encrypt, json)
	if source.InvestigatorSignature != nil {
	InvestigatorSignatureBytes, err := json.Marshal(source.InvestigatorSignature)
	if err != nil {
		errs.Set("InvestigatorSignature serialization", err)
	} else {
		result.InvestigatorSignatureEncrypted, err = crypto.EncryptData(ctx, InvestigatorSignatureBytes, dek)
		if err != nil {
			errs.Set("InvestigatorSignature encryption", err)
		}
	}
	}
	
	
	
	// Process SpecialInstructions (encrypt)
	if source.SpecialInstructions != nil {
	SpecialInstructionsBytes, err := encx.SerializeValue(source.SpecialInstructions)
	if err != nil {
		errs.Set("SpecialInstructions serialization", err)
	} else {
		result.SpecialInstructionsEncrypted, err = crypto.EncryptData(ctx, SpecialInstructionsBytes, dek)
		if err != nil {
			errs.Set("SpecialInstructions encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptMandateEncx decrypts the encrypted struct back to original
func DecryptMandateEncx(ctx context.Context, crypto encx.CryptoService, source *MandateEncx) (*Mandate, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Mandate{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.Status = source.Status
	
	result.CreatedAt = source.CreatedAt
	
	result.UpdatedAt = source.UpdatedAt
	
	result.IssueDate = source.IssueDate
	
	result.ValidFrom = source.ValidFrom
	
	result.ValidUntil = source.ValidUntil
	
	result.LinkedEstimateID = source.LinkedEstimateID
	
	result.Jurisdiction = source.Jurisdiction
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt CaseID
	if len(source.CaseIDEncrypted) > 0 {
		CaseIDBytes, err := crypto.DecryptData(ctx, source.CaseIDEncrypted, dek)
		if err != nil {
			errs.Set("CaseID decryption", err)
		} else {
			err = encx.DeserializeValue(CaseIDBytes, &result.CaseID)
			if err != nil {
				errs.Set("CaseID deserialization", err)
			}
		}
	}
	
	
	// Decrypt ClientID
	if len(source.ClientIDEncrypted) > 0 {
		ClientIDBytes, err := crypto.DecryptData(ctx, source.ClientIDEncrypted, dek)
		if err != nil {
			errs.Set("ClientID decryption", err)
		} else {
			err = encx.DeserializeValue(ClientIDBytes, &result.ClientID)
			if err != nil {
				errs.Set("ClientID deserialization", err)
			}
		}
	}
	
	
	// Decrypt MandateNumber
	if len(source.MandateNumberEncrypted) > 0 {
		MandateNumberBytes, err := crypto.DecryptData(ctx, source.MandateNumberEncrypted, dek)
		if err != nil {
			errs.Set("MandateNumber decryption", err)
		} else {
			err = encx.DeserializeValue(MandateNumberBytes, &result.MandateNumber)
			if err != nil {
				errs.Set("MandateNumber deserialization", err)
			}
		}
	}
	
	
	// Decrypt ScopeOfWork
	if len(source.ScopeOfWorkEncrypted) > 0 {
		ScopeOfWorkBytes, err := crypto.DecryptData(ctx, source.ScopeOfWorkEncrypted, dek)
		if err != nil {
			errs.Set("ScopeOfWork decryption", err)
		} else {
			err = encx.DeserializeValue(ScopeOfWorkBytes, &result.ScopeOfWork)
			if err != nil {
				errs.Set("ScopeOfWork deserialization", err)
			}
		}
	}
	
	
	// Decrypt TermsConditions
	if len(source.TermsConditionsEncrypted) > 0 {
		TermsConditionsBytes, err := crypto.DecryptData(ctx, source.TermsConditionsEncrypted, dek)
		if err != nil {
			errs.Set("TermsConditions decryption", err)
		} else {
			err = encx.DeserializeValue(TermsConditionsBytes, &result.TermsConditions)
			if err != nil {
				errs.Set("TermsConditions deserialization", err)
			}
		}
	}
	
	
	// Decrypt ClientSignature
	if len(source.ClientSignatureEncrypted) > 0 {
		ClientSignatureBytes, err := crypto.DecryptData(ctx, source.ClientSignatureEncrypted, dek)
		if err != nil {
			errs.Set("ClientSignature decryption", err)
		} else {
			err = json.Unmarshal(ClientSignatureBytes, &result.ClientSignature)
			if err != nil {
				errs.Set("ClientSignature deserialization", err)
			}
		}
	}
	
	
	// Decrypt InvestigatorSignature
	if len(source.InvestigatorSignatureEncrypted) > 0 {
		InvestigatorSignatureBytes, err := crypto.DecryptData(ctx, source.InvestigatorSignatureEncrypted, dek)
		if err != nil {
			errs.Set("InvestigatorSignature decryption", err)
		} else {
			err = json.Unmarshal(InvestigatorSignatureBytes, &result.InvestigatorSignature)
			if err != nil {
				errs.Set("InvestigatorSignature deserialization", err)
			}
		}
	}
	
	
	// Decrypt SpecialInstructions
	if len(source.SpecialInstructionsEncrypted) > 0 {
		SpecialInstructionsBytes, err := crypto.DecryptData(ctx, source.SpecialInstructionsEncrypted, dek)
		if err != nil {
			errs.Set("SpecialInstructions decryption", err)
		} else {
			err = encx.DeserializeValue(SpecialInstructionsBytes, &result.SpecialInstructions)
			if err != nil {
				errs.Set("SpecialInstructions deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
