// Code generated by encx-gen. DO NOT EDIT.
// Source: subject.go
// Generated: 2025-12-29T01:18:08+01:00

package subject

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// SubjectEncx represents the encrypted version of Subject
type SubjectEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	CaseID []uuid.UUID `db:"caseid" json:"caseid"`
	
	Roles []PersonRole `db:"roles" json:"roles"`
	
	CreatedAt time.Time `db:"createdat" json:"createdat"`
	
	
	LastnameEncrypted []byte `db:"lastname_encrypted" json:"lastname_encrypted"`
	
	LastnameHash string `db:"lastname_hash" json:"lastname_hash"`
	
	FirstnameEncrypted []byte `db:"firstname_encrypted" json:"firstname_encrypted"`
	
	FirstnameHash string `db:"firstname_hash" json:"firstname_hash"`
	
	EmailEncrypted []byte `db:"email_encrypted" json:"email_encrypted"`
	
	EmailHash string `db:"email_hash" json:"email_hash"`
	
	PhoneEncrypted []byte `db:"phone_encrypted" json:"phone_encrypted"`
	
	CityEncrypted []byte `db:"city_encrypted" json:"city_encrypted"`
	
	CityHash string `db:"city_hash" json:"city_hash"`
	
	PostalCodeEncrypted []byte `db:"postalcode_encrypted" json:"postalcode_encrypted"`
	
	PostalCodeHash string `db:"postalcode_hash" json:"postalcode_hash"`
	
	Address1Encrypted []byte `db:"address1_encrypted" json:"address1_encrypted"`
	
	Address1Hash string `db:"address1_hash" json:"address1_hash"`
	
	Address2Encrypted []byte `db:"address2_encrypted" json:"address2_encrypted"`
	
	Address2Hash string `db:"address2_hash" json:"address2_hash"`
	
	OccupationEncrypted []byte `db:"occupation_encrypted" json:"occupation_encrypted"`
	
	OccupationHash string `db:"occupation_hash" json:"occupation_hash"`
	
	NotesEncrypted []byte `db:"notes_encrypted" json:"notes_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessCaseSubjectEncx encrypts and hashes fields based on encx tags
func ProcessCaseSubjectEncx(ctx context.Context, crypto encx.CryptoService, source *Subject) (*SubjectEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &SubjectEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.CaseID = source.CaseID
	
	result.Roles = source.Roles
	
	result.CreatedAt = source.CreatedAt
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Lastname (encrypt + hash_basic)
	LastnameBytes, err := encx.SerializeValue(source.Lastname)
	if err != nil {
		errs.Set("Lastname serialization", err)
	} else {
		result.LastnameEncrypted, err = crypto.EncryptData(ctx, LastnameBytes, dek)
		if err != nil {
			errs.Set("Lastname encryption", err)
		}
		result.LastnameHash = crypto.HashBasic(ctx, LastnameBytes)
		
	}
	
	
	
	// Process Firstname (encrypt + hash_basic)
	FirstnameBytes, err := encx.SerializeValue(source.Firstname)
	if err != nil {
		errs.Set("Firstname serialization", err)
	} else {
		result.FirstnameEncrypted, err = crypto.EncryptData(ctx, FirstnameBytes, dek)
		if err != nil {
			errs.Set("Firstname encryption", err)
		}
		result.FirstnameHash = crypto.HashBasic(ctx, FirstnameBytes)
		
	}
	
	
	
	// Process Email (encrypt + hash_basic)
	EmailBytes, err := encx.SerializeValue(source.Email)
	if err != nil {
		errs.Set("Email serialization", err)
	} else {
		result.EmailEncrypted, err = crypto.EncryptData(ctx, EmailBytes, dek)
		if err != nil {
			errs.Set("Email encryption", err)
		}
		result.EmailHash = crypto.HashBasic(ctx, EmailBytes)
		
	}
	
	
	
	// Process Phone (encrypt)
	PhoneBytes, err := encx.SerializeValue(source.Phone)
	if err != nil {
		errs.Set("Phone serialization", err)
	} else {
		result.PhoneEncrypted, err = crypto.EncryptData(ctx, PhoneBytes, dek)
		if err != nil {
			errs.Set("Phone encryption", err)
		}
	}
	
	
	
	// Process City (encrypt + hash_basic)
	CityBytes, err := encx.SerializeValue(source.City)
	if err != nil {
		errs.Set("City serialization", err)
	} else {
		result.CityEncrypted, err = crypto.EncryptData(ctx, CityBytes, dek)
		if err != nil {
			errs.Set("City encryption", err)
		}
		result.CityHash = crypto.HashBasic(ctx, CityBytes)
		
	}
	
	
	
	// Process PostalCode (encrypt + hash_basic)
	PostalCodeBytes, err := encx.SerializeValue(source.PostalCode)
	if err != nil {
		errs.Set("PostalCode serialization", err)
	} else {
		result.PostalCodeEncrypted, err = crypto.EncryptData(ctx, PostalCodeBytes, dek)
		if err != nil {
			errs.Set("PostalCode encryption", err)
		}
		result.PostalCodeHash = crypto.HashBasic(ctx, PostalCodeBytes)
		
	}
	
	
	
	// Process Address1 (encrypt + hash_basic)
	Address1Bytes, err := encx.SerializeValue(source.Address1)
	if err != nil {
		errs.Set("Address1 serialization", err)
	} else {
		result.Address1Encrypted, err = crypto.EncryptData(ctx, Address1Bytes, dek)
		if err != nil {
			errs.Set("Address1 encryption", err)
		}
		result.Address1Hash = crypto.HashBasic(ctx, Address1Bytes)
		
	}
	
	
	
	// Process Address2 (encrypt + hash_basic)
	Address2Bytes, err := encx.SerializeValue(source.Address2)
	if err != nil {
		errs.Set("Address2 serialization", err)
	} else {
		result.Address2Encrypted, err = crypto.EncryptData(ctx, Address2Bytes, dek)
		if err != nil {
			errs.Set("Address2 encryption", err)
		}
		result.Address2Hash = crypto.HashBasic(ctx, Address2Bytes)
		
	}
	
	
	
	// Process Occupation (encrypt + hash_basic)
	OccupationBytes, err := encx.SerializeValue(source.Occupation)
	if err != nil {
		errs.Set("Occupation serialization", err)
	} else {
		result.OccupationEncrypted, err = crypto.EncryptData(ctx, OccupationBytes, dek)
		if err != nil {
			errs.Set("Occupation encryption", err)
		}
		result.OccupationHash = crypto.HashBasic(ctx, OccupationBytes)
		
	}
	
	
	
	// Process Notes (encrypt)
	NotesBytes, err := encx.SerializeValue(source.Notes)
	if err != nil {
		errs.Set("Notes serialization", err)
	} else {
		result.NotesEncrypted, err = crypto.EncryptData(ctx, NotesBytes, dek)
		if err != nil {
			errs.Set("Notes encryption", err)
		}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptCaseSubjectEncx decrypts the encrypted struct back to original
func DecryptCaseSubjectEncx(ctx context.Context, crypto encx.CryptoService, source *SubjectEncx) (*Subject, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &Subject{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.CaseID = source.CaseID
	
	result.Roles = source.Roles
	
	result.CreatedAt = source.CreatedAt
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Lastname
	if len(source.LastnameEncrypted) > 0 {
		LastnameBytes, err := crypto.DecryptData(ctx, source.LastnameEncrypted, dek)
		if err != nil {
			errs.Set("Lastname decryption", err)
		} else {
			err = encx.DeserializeValue(LastnameBytes, &result.Lastname)
			if err != nil {
				errs.Set("Lastname deserialization", err)
			}
		}
	}
	
	
	// Decrypt Firstname
	if len(source.FirstnameEncrypted) > 0 {
		FirstnameBytes, err := crypto.DecryptData(ctx, source.FirstnameEncrypted, dek)
		if err != nil {
			errs.Set("Firstname decryption", err)
		} else {
			err = encx.DeserializeValue(FirstnameBytes, &result.Firstname)
			if err != nil {
				errs.Set("Firstname deserialization", err)
			}
		}
	}
	
	
	// Decrypt Email
	if len(source.EmailEncrypted) > 0 {
		EmailBytes, err := crypto.DecryptData(ctx, source.EmailEncrypted, dek)
		if err != nil {
			errs.Set("Email decryption", err)
		} else {
			err = encx.DeserializeValue(EmailBytes, &result.Email)
			if err != nil {
				errs.Set("Email deserialization", err)
			}
		}
	}
	
	
	// Decrypt Phone
	if len(source.PhoneEncrypted) > 0 {
		PhoneBytes, err := crypto.DecryptData(ctx, source.PhoneEncrypted, dek)
		if err != nil {
			errs.Set("Phone decryption", err)
		} else {
			err = encx.DeserializeValue(PhoneBytes, &result.Phone)
			if err != nil {
				errs.Set("Phone deserialization", err)
			}
		}
	}
	
	
	// Decrypt City
	if len(source.CityEncrypted) > 0 {
		CityBytes, err := crypto.DecryptData(ctx, source.CityEncrypted, dek)
		if err != nil {
			errs.Set("City decryption", err)
		} else {
			err = encx.DeserializeValue(CityBytes, &result.City)
			if err != nil {
				errs.Set("City deserialization", err)
			}
		}
	}
	
	
	// Decrypt PostalCode
	if len(source.PostalCodeEncrypted) > 0 {
		PostalCodeBytes, err := crypto.DecryptData(ctx, source.PostalCodeEncrypted, dek)
		if err != nil {
			errs.Set("PostalCode decryption", err)
		} else {
			err = encx.DeserializeValue(PostalCodeBytes, &result.PostalCode)
			if err != nil {
				errs.Set("PostalCode deserialization", err)
			}
		}
	}
	
	
	// Decrypt Address1
	if len(source.Address1Encrypted) > 0 {
		Address1Bytes, err := crypto.DecryptData(ctx, source.Address1Encrypted, dek)
		if err != nil {
			errs.Set("Address1 decryption", err)
		} else {
			err = encx.DeserializeValue(Address1Bytes, &result.Address1)
			if err != nil {
				errs.Set("Address1 deserialization", err)
			}
		}
	}
	
	
	// Decrypt Address2
	if len(source.Address2Encrypted) > 0 {
		Address2Bytes, err := crypto.DecryptData(ctx, source.Address2Encrypted, dek)
		if err != nil {
			errs.Set("Address2 decryption", err)
		} else {
			err = encx.DeserializeValue(Address2Bytes, &result.Address2)
			if err != nil {
				errs.Set("Address2 deserialization", err)
			}
		}
	}
	
	
	// Decrypt Occupation
	if len(source.OccupationEncrypted) > 0 {
		OccupationBytes, err := crypto.DecryptData(ctx, source.OccupationEncrypted, dek)
		if err != nil {
			errs.Set("Occupation decryption", err)
		} else {
			err = encx.DeserializeValue(OccupationBytes, &result.Occupation)
			if err != nil {
				errs.Set("Occupation deserialization", err)
			}
		}
	}
	
	
	// Decrypt Notes
	if len(source.NotesEncrypted) > 0 {
		NotesBytes, err := crypto.DecryptData(ctx, source.NotesEncrypted, dek)
		if err != nil {
			errs.Set("Notes decryption", err)
		} else {
			err = encx.DeserializeValue(NotesBytes, &result.Notes)
			if err != nil {
				errs.Set("Notes deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
