// Code generated by encx-gen. DO NOT EDIT.
// Source: auth.go
// Generated: 2025-12-02T20:43:16+01:00

package testutils

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// UserEncx represents the encrypted version of User
type UserEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	State string `db:"state" json:"state"`
	
	
	EmailEncrypted []byte `db:"email_encrypted" json:"email_encrypted"`
	
	EmailHash string `db:"email_hash" json:"email_hash"`
	
	FirstNameEncrypted []byte `db:"firstname_encrypted" json:"firstname_encrypted"`
	
	LastNameEncrypted []byte `db:"lastname_encrypted" json:"lastname_encrypted"`
	
	PasswordHashSecure string `db:"password_hash_secure" json:"password_hash_secure"`
	
	TelephoneEncrypted []byte `db:"telephone_encrypted" json:"telephone_encrypted"`
	
	TelephoneHash string `db:"telephone_hash" json:"telephone_hash"`
	
	RoleEncrypted []byte `db:"role_encrypted" json:"role_encrypted"`
	
	CreatedAtEncrypted []byte `db:"createdat_encrypted" json:"createdat_encrypted"`
	
	LoggedInAtEncrypted []byte `db:"loggedinat_encrypted" json:"loggedinat_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessUserEncx encrypts and hashes fields based on encx tags
func ProcessUserEncx(ctx context.Context, crypto encx.CryptoService, source *User) (*UserEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &UserEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.State = source.State
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Email (encrypt + hash_basic)
	EmailBytes, err := encx.SerializeValue(source.Email)
	if err != nil {
		errs.Set("Email serialization", err)
	} else {
		result.EmailEncrypted, err = crypto.EncryptData(ctx, EmailBytes, dek)
		if err != nil {
			errs.Set("Email encryption", err)
		}
		result.EmailHash = crypto.HashBasic(ctx, EmailBytes)
		
	}
	
	
	
	// Process FirstName (encrypt)
	FirstNameBytes, err := encx.SerializeValue(source.FirstName)
	if err != nil {
		errs.Set("FirstName serialization", err)
	} else {
		result.FirstNameEncrypted, err = crypto.EncryptData(ctx, FirstNameBytes, dek)
		if err != nil {
			errs.Set("FirstName encryption", err)
		}
	}
	
	
	
	// Process LastName (encrypt)
	LastNameBytes, err := encx.SerializeValue(source.LastName)
	if err != nil {
		errs.Set("LastName serialization", err)
	} else {
		result.LastNameEncrypted, err = crypto.EncryptData(ctx, LastNameBytes, dek)
		if err != nil {
			errs.Set("LastName encryption", err)
		}
	}
	
	
	
	// Process Password (hash_secure)
	PasswordBytes, err := encx.SerializeValue(source.Password)
	if err != nil {
		errs.Set("Password serialization", err)
	} else {
		result.PasswordHashSecure, err = crypto.HashSecure(ctx, PasswordBytes)
		if err != nil {
			errs.Set("Password secure hash", err)
		}
	}
	
	
	
	// Process Telephone (encrypt + hash_basic)
	TelephoneBytes, err := encx.SerializeValue(source.Telephone)
	if err != nil {
		errs.Set("Telephone serialization", err)
	} else {
		result.TelephoneEncrypted, err = crypto.EncryptData(ctx, TelephoneBytes, dek)
		if err != nil {
			errs.Set("Telephone encryption", err)
		}
		result.TelephoneHash = crypto.HashBasic(ctx, TelephoneBytes)
		
	}
	
	
	
	// Process Role (encrypt)
	RoleBytes, err := encx.SerializeValue(source.Role)
	if err != nil {
		errs.Set("Role serialization", err)
	} else {
		result.RoleEncrypted, err = crypto.EncryptData(ctx, RoleBytes, dek)
		if err != nil {
			errs.Set("Role encryption", err)
		}
	}
	
	
	
	// Process CreatedAt (encrypt)
	if !source.CreatedAt.IsZero() {
	CreatedAtBytes, err := encx.SerializeValue(source.CreatedAt)
	if err != nil {
		errs.Set("CreatedAt serialization", err)
	} else {
		result.CreatedAtEncrypted, err = crypto.EncryptData(ctx, CreatedAtBytes, dek)
		if err != nil {
			errs.Set("CreatedAt encryption", err)
		}
	}
	}
	
	
	
	// Process LoggedInAt (encrypt)
	if !source.LoggedInAt.IsZero() {
	LoggedInAtBytes, err := encx.SerializeValue(source.LoggedInAt)
	if err != nil {
		errs.Set("LoggedInAt serialization", err)
	} else {
		result.LoggedInAtEncrypted, err = crypto.EncryptData(ctx, LoggedInAtBytes, dek)
		if err != nil {
			errs.Set("LoggedInAt encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptUserEncx decrypts the encrypted struct back to original
func DecryptUserEncx(ctx context.Context, crypto encx.CryptoService, source *UserEncx) (*User, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &User{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	
	result.State = source.State
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Email
	if len(source.EmailEncrypted) > 0 {
		EmailBytes, err := crypto.DecryptData(ctx, source.EmailEncrypted, dek)
		if err != nil {
			errs.Set("Email decryption", err)
		} else {
			err = encx.DeserializeValue(EmailBytes, &result.Email)
			if err != nil {
				errs.Set("Email deserialization", err)
			}
		}
	}
	
	
	// Decrypt FirstName
	if len(source.FirstNameEncrypted) > 0 {
		FirstNameBytes, err := crypto.DecryptData(ctx, source.FirstNameEncrypted, dek)
		if err != nil {
			errs.Set("FirstName decryption", err)
		} else {
			err = encx.DeserializeValue(FirstNameBytes, &result.FirstName)
			if err != nil {
				errs.Set("FirstName deserialization", err)
			}
		}
	}
	
	
	// Decrypt LastName
	if len(source.LastNameEncrypted) > 0 {
		LastNameBytes, err := crypto.DecryptData(ctx, source.LastNameEncrypted, dek)
		if err != nil {
			errs.Set("LastName decryption", err)
		} else {
			err = encx.DeserializeValue(LastNameBytes, &result.LastName)
			if err != nil {
				errs.Set("LastName deserialization", err)
			}
		}
	}
	
	
	// Decrypt Telephone
	if len(source.TelephoneEncrypted) > 0 {
		TelephoneBytes, err := crypto.DecryptData(ctx, source.TelephoneEncrypted, dek)
		if err != nil {
			errs.Set("Telephone decryption", err)
		} else {
			err = encx.DeserializeValue(TelephoneBytes, &result.Telephone)
			if err != nil {
				errs.Set("Telephone deserialization", err)
			}
		}
	}
	
	
	// Decrypt Role
	if len(source.RoleEncrypted) > 0 {
		RoleBytes, err := crypto.DecryptData(ctx, source.RoleEncrypted, dek)
		if err != nil {
			errs.Set("Role decryption", err)
		} else {
			err = encx.DeserializeValue(RoleBytes, &result.Role)
			if err != nil {
				errs.Set("Role deserialization", err)
			}
		}
	}
	
	
	// Decrypt CreatedAt
	if len(source.CreatedAtEncrypted) > 0 {
		CreatedAtBytes, err := crypto.DecryptData(ctx, source.CreatedAtEncrypted, dek)
		if err != nil {
			errs.Set("CreatedAt decryption", err)
		} else {
			err = encx.DeserializeValue(CreatedAtBytes, &result.CreatedAt)
			if err != nil {
				errs.Set("CreatedAt deserialization", err)
			}
		}
	}
	
	
	// Decrypt LoggedInAt
	if len(source.LoggedInAtEncrypted) > 0 {
		LoggedInAtBytes, err := crypto.DecryptData(ctx, source.LoggedInAtEncrypted, dek)
		if err != nil {
			errs.Set("LoggedInAt decryption", err)
		} else {
			err = encx.DeserializeValue(LoggedInAtBytes, &result.LoggedInAt)
			if err != nil {
				errs.Set("LoggedInAt deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
