// Code generated by encx-gen. DO NOT EDIT.
// Source: auth.go
// Generated: 2025-12-04T22:52:20+01:00

package testutils

import (
	"context"
	"time"

	"github.com/hengadev/errsx"
	"github.com/hengadev/encx"
	
	"github.com/google/uuid"
	
)

// UserEncx represents the encrypted version of User
type UserEncx struct {
	
	ID uuid.UUID `db:"id" json:"id"`
	
	
	EmailHash string `db:"email_hash" json:"email_hash"`
	
	EmailEncrypted []byte `db:"email_encrypted" json:"email_encrypted"`
	
	PasswordHashSecure string `db:"password_hash_secure" json:"password_hash_secure"`
	
	RoleEncrypted []byte `db:"role_encrypted" json:"role_encrypted"`
	
	CreatedAtEncrypted []byte `db:"createdat_encrypted" json:"createdat_encrypted"`
	

	// Essential encryption fields
	DEKEncrypted  []byte `db:"dek_encrypted" json:"dek_encrypted"`
	KeyVersion    int    `db:"key_version" json:"key_version"`

	// Metadata
	Metadata      encx.EncryptionMetadata `db:"metadata" json:"metadata"`
}

// ProcessUserEncx encrypts and hashes fields based on encx tags
func ProcessUserEncx(ctx context.Context, crypto encx.CryptoService, source *User) (*UserEncx, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &UserEncx{
		Metadata: encx.EncryptionMetadata{
			KEKAlias:         crypto.GetAlias(),
			EncryptionTime:   time.Now().Unix(),
			GeneratorVersion: "1.0.0",
		},
	}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	

	// Generate DEK
	dek, err := crypto.GenerateDEK()
	if err != nil {
		errs.Set("DEK generation", err)
		return result, errs.AsError()
	}

	
	
	// Process Email (hash_basic + encrypt)
	EmailBytes, err := encx.SerializeValue(source.Email)
	if err != nil {
		errs.Set("Email serialization", err)
	} else {
		result.EmailHash = crypto.HashBasic(ctx, EmailBytes)
		result.EmailEncrypted, err = crypto.EncryptData(ctx, EmailBytes, dek)
		if err != nil {
			errs.Set("Email encryption", err)
		}
		
	}
	
	
	
	// Process Password (hash_secure)
	PasswordBytes, err := encx.SerializeValue(source.Password)
	if err != nil {
		errs.Set("Password serialization", err)
	} else {
		result.PasswordHashSecure, err = crypto.HashSecure(ctx, PasswordBytes)
		if err != nil {
			errs.Set("Password secure hash", err)
		}
	}
	
	
	
	// Process Role (encrypt)
	RoleBytes, err := encx.SerializeValue(source.Role)
	if err != nil {
		errs.Set("Role serialization", err)
	} else {
		result.RoleEncrypted, err = crypto.EncryptData(ctx, RoleBytes, dek)
		if err != nil {
			errs.Set("Role encryption", err)
		}
	}
	
	
	
	// Process CreatedAt (encrypt)
	if !source.CreatedAt.IsZero() {
	CreatedAtBytes, err := encx.SerializeValue(source.CreatedAt)
	if err != nil {
		errs.Set("CreatedAt serialization", err)
	} else {
		result.CreatedAtEncrypted, err = crypto.EncryptData(ctx, CreatedAtBytes, dek)
		if err != nil {
			errs.Set("CreatedAt encryption", err)
		}
	}
	}
	
	

	// Encrypt and store DEK
	result.DEKEncrypted, err = crypto.EncryptDEK(ctx, dek)
	if err != nil {
		errs.Set("DEK encryption", err)
	}

	// Get and set the current KEK version
	result.KeyVersion, err = crypto.GetCurrentKEKVersion(ctx, crypto.GetAlias())
	if err != nil {
		errs.Set("KEK version retrieval", err)
	}

	return result, errs.AsError()
}

// DecryptUserEncx decrypts the encrypted struct back to original
func DecryptUserEncx(ctx context.Context, crypto encx.CryptoService, source *UserEncx) (*User, error) {
	var errs errsx.Map

	// Initialize result struct
	result := &User{}

	// Copy plain fields (non-encx fields)
	
	result.ID = source.ID
	

	// Decrypt DEK
	dek, err := crypto.DecryptDEKWithVersion(ctx, source.DEKEncrypted, source.KeyVersion)
	if err != nil {
		errs.Set("DEK decryption", err)
		return result, errs.AsError()
	}

	
	
	// Decrypt Email
	if len(source.EmailEncrypted) > 0 {
		EmailBytes, err := crypto.DecryptData(ctx, source.EmailEncrypted, dek)
		if err != nil {
			errs.Set("Email decryption", err)
		} else {
			err = encx.DeserializeValue(EmailBytes, &result.Email)
			if err != nil {
				errs.Set("Email deserialization", err)
			}
		}
	}
	
	
	// Decrypt Role
	if len(source.RoleEncrypted) > 0 {
		RoleBytes, err := crypto.DecryptData(ctx, source.RoleEncrypted, dek)
		if err != nil {
			errs.Set("Role decryption", err)
		} else {
			err = encx.DeserializeValue(RoleBytes, &result.Role)
			if err != nil {
				errs.Set("Role deserialization", err)
			}
		}
	}
	
	
	// Decrypt CreatedAt
	if len(source.CreatedAtEncrypted) > 0 {
		CreatedAtBytes, err := crypto.DecryptData(ctx, source.CreatedAtEncrypted, dek)
		if err != nil {
			errs.Set("CreatedAt decryption", err)
		} else {
			err = encx.DeserializeValue(CreatedAtBytes, &result.CreatedAt)
			if err != nil {
				errs.Set("CreatedAt deserialization", err)
			}
		}
	}
	

	return result, errs.AsError()
}
