---
- name: Daemon-reload and enable cluo service
  ansible.builtin.systemd:
    daemon_reload: true
    name: cluo
    enabled: true
    state: started

- name: Reload Caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
